---
### Binary Sensors ###

binary_sensor:
  # Workday
  - platform: workday
    name: workday
    country: US

  # Worknight
  - platform: workday
    name: worknight
    country: US
    days_offset: 1
