---
### Home Assistant Core Configurations ###

# Show links to resources in log and frontend
# introduction:

# Enable iOS frontend
ios:

# Enables configuration UI
config:

# Incorporate latest changes
default_config:

# Person component
person:

homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks: !secret trusted_networks

# Use MariaDB Add-on for Database
recorder:
  db_url: !secret mysql_uri
  purge_keep_days: 7

# Enable logging
logger:
  default: warn

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Home Assistant Cloud
cloud:
