---
### Home Assistant Core Configurations ###

# Show links to resources in log and frontend
# introduction:

# Enable iOS frontend
ios:

# Enables configuration UI
config:

# Incorporate latest changes
default_config:

# Person component
person:

homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks: !secret trusted_networks

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
# updater:
# Deprecated with 2021.4.0
# Optional, allows Home Assistant developers to focus on popular components.
# include_used_components: true

# Use MariaDB Add-on for Database
recorder:
  db_url: !secret mysql_uri
  purge_keep_days: 7
  # Deprecated
  # purge_interval: 1

# Enable logging
logger:
  default: warn

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
# map: # Deprecated

# Track the sun
sun:

# Home Assistant Cloud
cloud:
# Universal Plug and Play
# upnp: # DEPRECATED
