---
### Alarm System ###
homeassistant:
  customize:
    alarm_control_panel.home:
      friendly_name: Alarm System
      icon: mdi:shield-home
    sensor.home_keypad:
      friendly_name: Alarm Keypad
      icon: mdi:calculator
    binary_sensor.front_door:
      icon: mdi:door
    binary_sensor.back_door:
      icon: mdi:door
    binary_sensor.garage_door:
      icon: mdi:door
# From configuration.yaml

# Envisalink
envisalink:
  host: !secret envisalink_host
  panel_type: HONEYWELL
  user_name: !secret envisalink_username
  password: !secret envisalink_password
  code: !secret alarm_code
  port: !secret envisalink_port
  evl_version: 4
  keepalive_interval: 60
  zonedump_interval: 30
  panic_type: Police
  zones:
    1:
      name: 'Front Door'
      type: 'opening'
    2:
      name: 'Back Door'
      type: 'opening'
    3:
      name: 'Garage Door'
      type: 'opening'
    4:
      name: 'Glass Break'
      type: 'problem'
    10:
      name: 'Living Room'
      type: 'motion'
  partitions:
    1:
      name: 'Home'
