---
### HomeKit ###

# From configuration.yaml
# HomeKit
homekit:
  auto_start: true
  pincode: !secret homekit_pin
  port: 51827
  filter:
    include_entities:
      - climate.homekit_downstairs
      - climate.homekit_upstairs
      - light.master_bedroom_floor_lamp
      - light.master_bedroom_table_lamps
      - light.sitting_room_floor_lamp
      - light.outdoor_lights
      - light.back_yard_string_lights
      - lock.front_door
      - lock.back_door
      - alarm_control_panel.home
      - switch.downstairs_vacuum
      - switch.upstairs_vacuum
      - light.dining_room_chandelier
      - light.kitchen_chandelier
      - cover.main_garage_door
      - cover.second_garage_door
      - light.living_room_ceiling_fan
      - fan.master_bedroom_ceiling_fan
      - fan.living_room_ceiling_fan
      - camera.dogcam

# The following automation delays HomeKit while the Z-Wave network starts up.
automation:
  - alias: 'HomeKit - Delayed Start'
    trigger:
      - platform: event
        event_type: zwave.network_ready
      - platform: event
        event_type: zwave.network_complete
      - platform: event
        event_type: zwave.network_complete_some_dead
    action:
      - service: homekit.start