### HomeKit ###

# From configuration.yaml
# HomeKit
homekit:
  auto_start: false
  pincode: !secret homekit_pin
  port: 51827
  filter:
    include_entities:
      - climate.homekit_downstairs
      - climate.homekit_upstairs
      - light.master_bedroom_floor_lamp
      - light.master_bedroom_table_lamps
      - light.sitting_room_floor_lamp
      - light.outdoor_lights
      - lock.front_door
      - lock.back_door
      - alarm_control_panel.home
      - switch.vaccum_downstairs
      - light.dining_room_chandelier
      - light.kitchen_chandelier
      - cover.garage_door_01
      - cover.garage_door_02

# The following automation delays HomeKit while the Z-Wave network starts up.
automation:
  - alias: 'HomeKit - Delayed Start'
    trigger:
      - platform: event
        event_type: zwave.network_ready
      - platform: event
        event_type: zwave.network_complete
      - platform: event
        event_type: zwave.network_complete_some_dead
    action:
      - service: homekit.start