---
### OctoPrint ###

# Pulling values via MQTT rather than API.
# Using official MQTT plugin
# https://github.com/OctoPrint/OctoPrint-MQTT
# And 3rd party Home Assistant discovery plugin
# https://github.com/cmroche/OctoPrint-HomeAssistant

# Why MQTT > API?
# https://github.com/cmroche/OctoPrint-HomeAssistant#why-use-this-plugin

# Retaining API Configuration for now.
# octoprint:
#   - host: !secret octoprint_host
#     api_key: !secret octoprint_api_key
#     name: !secret octoprint_name
#     bed: true
#     number_of_tools: 1

# Values coming from OctoPrint are being converted to stupid degrees.
# Convert back to real degrees.
homeassistant:
  customize:
    sensor.octoprint_bed_target:
      unit_of_measurement: 'C'
    sensor.octoprint_bed_temperature:
      unit_of_measurement: 'C'
    sensor.octoprint_tool_0_target:
      unit_of_measurement: 'C'
    sensor.octoprint_tool_0_temperature:
      unit_of_measurement: 'C'

# Bring in the camera
camera:
  - platform: generic
    name: OctoPrint CR-6 SE
    still_image_url: http://octopi-cr6.apocrathia.com/webcam/?action=snapshot
    stream_source: http://octopi-cr6.apocrathia.com/webcam/?action=stream

# Automation ideas
# - Announce when a print is done
# - Turn on room lights when printing (For Octolapse and TSD)