---
### Sensors ###

sensor:
  # Time & Date
  - platform: time_date
    display_options:
      - 'time'
      - 'date'

  # Pirate Weather
  - platform: pirateweather
    api_key: !secret pirateweather_api_key
    # Use a prime number to simulate randomness
    scan_interval: '00:17:17'
    monitored_conditions:
      - summary
      - temperature
      - precip_probability
      - precip_type
      - humidity
      - cloud_cover
      - nearest_storm_distance
      - precip_intensity
      - wind_speed

# Template
template:
  - sensor:
      - default_entity_id: sensor.serenity
        name: Serenity
        state: Catting
