---
### Sensors ###

sensor:
  # Weather prediction
  #  - platform: yr

  - platform: moon

  # Time & Date
  - platform: time_date
    display_options:
      - 'time'
      - 'date'

  # Weather forecast
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - summary

  # Pirate Weather
  - platform: pirateweather
    api_key: !secret pirateweather_api_key
    scan_interval: '00:17:17' # Use a prime number to simulate randomness
    monitored_conditions:
      - summary
      - temperature
      - precip_probability
      - precip_type
      - humidity
      - cloud_cover
      - nearest_storm_distance
      - precip_intensity
      - wind_speed

  # Steam
  - platform: steam_online
    # entity_namespace: steam
    api_key: !secret steam_api_key
    accounts:
      - !secret steam_account_id

  # Certification Expiration
  - platform: cert_expiry
    host: !secret hass_url
    port: !secret hass_port

  # Twitch
  - platform: twitch
    client_id: !secret twitch_client_id
    client_secret: !secret twitch_client_secret
    token: !secret twitch_client_token
    channels:
      - Apocrathia
      - PB_Undesirables
      - NineFoot3

  # Template
  - platform: template
    sensors:
      # Because we love our pets
      serenity:
        friendly_name: 'Serenity'
        value_template: >-
          Catting
      michio: # https://www.instagram.com/michiothedoge/
        friendly_name: 'Michio'
        value_template: >-
          Pupping
      sagan: # https://www.instagram.com/saganthepomsky/
        friendly_name: 'Sagan'
        value_template: >-
          Pupping
      hubble: # https://www.instagram.com/hubbletheaussie/
        friendly_name: 'Hubble'
        value_template: >-
          Pupping
