---
### Sensors ###

sensor:
  # Weather prediction
  - platform: yr

  - platform: moon

  # Time & Date
  - platform: time_date
    display_options:
      - 'time'
      - 'date'

  # Weather forecast
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - summary

  # Steam
  - platform: steam_online
    # entity_namespace: steam
    api_key: !secret steam_api_key
    accounts:
      - !secret steam_account_id

  # Certification Expiration
  - platform: cert_expiry
    host: !secret hass_url
    port: !secret hass_port

  # Template
  - platform: template
    sensors:
      # Because we love our pets
      serenity:
        friendly_name: 'Serenity'
        value_template: >-
          Catting
      sagan: # https://www.instagram.com/saganthepomsky/
        friendly_name: 'Sagan'
        value_template: >-
          Pupping
      hubble: # https://www.instagram.com/hubbletheaussie/
        friendly_name: 'Hubble'
        value_template: >-
          Pupping
