---
### Sensors ###

sensor:
  # Weather prediction
  #  - platform: yr

  # - platform: moon

  # Time & Date
  - platform: time_date
    display_options:
      - 'time'
      - 'date'

  # Weather forecast
  # - platform: darksky
  #   api_key: !secret darksky_api_key
  #   monitored_conditions:
  #     - summary

  # Pirate Weather
  - platform: pirateweather
    api_key: !secret pirateweather_api_key
    # Use a prime number to simulate randomness
    scan_interval: '00:17:17'
    monitored_conditions:
      - summary
      - temperature
      - precip_probability
      - precip_type
      - humidity
      - cloud_cover
      - nearest_storm_distance
      - precip_intensity
      - wind_speed

  # Certification Expiration
  # - platform: cert_expiry
  #   host: !secret hass_url
  #   port: !secret hass_port

  # Twitch
  # - platform: twitch
  #   client_id: !secret twitch_client_id
  #   client_secret: !secret twitch_client_secret
  #   token: !secret twitch_client_token
  #   channels:
  #     - Apocrathia
  #     - PB_Undesirables
  #     - NineFoot3

  # Template
  - platform: template
    sensors:
      # Because we love our pets
      serenity:
        friendly_name: 'Serenity'
        value_template: >-
          Catting
      # https://www.instagram.com/michiothedoge/
      michio:
        friendly_name: 'Michio'
        value_template: >-
          Pupping
      # https://www.instagram.com/saganthepomsky/
