- id: '1533651116446'
  alias: Test - Downstairs Roomba Notification
  initial_state: 'off'
  trigger:
  - entity_id: vacuum.roomba_downstairs
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - alias: ''
    data:
      message: The Downstairs Roomba has stopped.
    service: notify.ios_ians_iphone
