################################################################################
- id: front_porch_lights_nighttime
  alias: 'Front Porch - Nighttime Lighting'
  trigger:
    - platform: state
      entity_id: sun.sun
      from: 'above_horizon'
      to: 'below_horizon'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: light.front_porch_lights
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.front_porch_lights
        profile: relax
        brightness_pct: 25
        transition: 900
################################################################################

################################################################################
- id: front_porch_lights_daytime
  alias: 'Front Porch - Daytime Lighting'
  trigger:
    - platform: state
      entity_id: sun.sun
      from: 'below_horizon'
      to: 'above_horizon'
  action:
    - service: light.turn_off
      data:
        entity_id: light.front_porch_lights
        transition: 900
################################################################################

################################################################################
- id: front_door_nighttime_motion_initial
  alias: 'Front Porch - Nighttime Motion'
  trigger:
    - platform: state
      entity_id: binary_sensor.ring_front_door_motion
      from: 'off'
      to: 'on'
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
# Transition to this profile, even if on
    - service: light.turn_on
      data:
        entity_id: light.front_porch_lights
        profile: energize
        transition: 1
################################################################################

################################################################################
- id: front_door_nighttime_motion_idle
  alias: 'Front Porch - Nighttime Motion Idle'
  trigger:
    - platform: state
      entity_id: binary_sensor.ring_front_door_motion
      from: 'on'
      to: 'off'
      for:
        minutes: 5
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
# Transition back to a preset profile/scene
    - service: light.turn_on
      data:
        entity_id: light.front_porch_lights
        profile: relax
        brightness_pct: 25
        transition: 5
################################################################################

################################################################################
- id: living_room_lights_nighttime
  alias: 'Living Room - Nighttime Lighting'
  trigger:
    - platform: state
      entity_id: sun.sun
      from: 'above_horizon'
      to: 'below_horizon'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: light.floop_lamp
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.floop_lamp
        profile: relax
        brightness_pct: 25
        transition: 900
################################################################################

################################################################################
- id: living_room_lights_daytime
  alias: 'Living Room - Daytime Lighting'
  trigger:
    - platform: state
      entity_id: sun.sun
      from: 'below_horizon'
      to: 'above_horizon'
  action:
    - service: light.turn_off
      data:
        entity_id: light.floop_lamp
        transition: 900
################################################################################

################################################################################
- id: location_home
  alias: "Location - Home"
  trigger:
    - platform: state
      entity_id: 
      - device_tracker.network_ians_iphone
      - device_tracker.network_aimees_iphone
      - device_tracker.network_richards_iphone
      to: 'home'
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: device_tracker.network_ians_iphone
      state: 'not_home'
    - condition: state
      entity_id: device_tracker.network_aimees_iphone
      state: 'not_home'
    - condition: state
      entity_id: device_tracker.network_richards_iphone
      state: 'not_home'
  action:
# Change this to a scene later on
    - service: nest.set_mode
      data:
        home_mode: home
        structure:
          - Percivale
    - service: alarm_control_panel.alarm_disarm
      data:
        entity_id: alarm_control_panel.home
        code: !secret alarm_code
################################################################################

################################################################################
- id: location_away
  alias: "Location - Away"
  trigger:
    - platform: state
      entity_id: 
      - device_tracker.network_ians_iphone
      - device_tracker.network_aimees_iphone
      - device_tracker.network_richards_iphone
      to: 'not_home'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.network_ians_iphone
      state: 'not_home'
    - condition: state
      entity_id: device_tracker.network_aimees_iphone
      state: 'not_home'
    - condition: state
      entity_id: device_tracker.network_richards_iphone
      state: 'not_home'
  action:
# Change this to a scene later on
    - service: nest.set_mode
      data:
        home_mode: away
        structure:
          - Percivale
    - service: alarm_control_panel.alarm_arm_away
      data:
        entity_id: alarm_control_panel.home
        code: !secret alarm_code
################################################################################

################################################################################
#- id: nighttime_mode
#  alias: "Nighttime Mode"
#  trigger:
#    - platform: time
#      at: '21:00:00'
################################################################################

################################################################################
#- id: living_room_motion
#  alias: 'Living Room Motion'
#  trigger:
#    - platform: state
#      entity_id: binary_sensor.living_room_motion
#      from: 'off'
#      to: 'on'
#  action:
#    - service: notify.notify
#      data:
#        message: 'Living Room Motion'
################################################################################

################################################################################
- id: notification_update
  alias: 'Notification - Update Available'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.notify
    data:
      message: 'An update for Home Assistant is available.'
################################################################################

################################################################################
- id: notification_new_device
  alias: 'Notification - New Device'
  trigger:
    - platform: event
      event_type: device_tracker_new_device
  action:
    - service: notify.notify
      data_template:
        message: >
          Home Assistant has discovered a new device:
          {{trigger.event.data.entity_id}}
        title: New Device
################################################################################

################################################################################
- id: notification_restart
  alias: 'Notification - Home Assistant Restart'
  trigger:
    platform: homeassistant
    event: start
  action:
    service: notify.notify
    data:
      message: 'Home Assistant has restarted.'
################################################################################

################################################################################
#- id: notification_battery_low
#  alias: 'Notification - Battery Low'
#  trigger:
#    platform: numeric_state
#    entity_id: 
#    - device_tracker.network_ians_iphone
#    - device_tracker.network_aimees_iphone
#    - device_tracker.network_richards_iphone
#    value_template: >
#      {{ state.attributes.battery | int }}
#    below: 25
#  action:
#    - service: notify.notify
#      data_template:
#        title: 'Low Battery'
#        message: >
#          Please check the battery for the following device:
#          {{trigger.event.data.entity_id}}
# {{ trigger.to_state.attributes.friendly_name }}
#{%- set threshold = 100 -%}
#{%- set domains = ['light', 'switch', 'sensor', 'lock'] -%}
#{%- for domain in domains -%}
#   {%- for item in states[domain] %}
#       {%- if ((item.attributes.battery_level is defined and item.attributes['battery_level'] | int < threshold) or ("battery" in item.name | lower and ((item.state | int < threshold and item.state|int != 0) or item.state | lower == "low" or item.state | lower == "unknown"))) -%}
#           {{ item.attributes.friendly_name }}
#       {% endif %}
#   {%- endfor -%}
#{%- endfor -%}
#################################################################################

################################################################################
#  # IF: { sun.sun goes under horizon } THEN: { set theme to night mode }
#- id: theme_automatic
#  alias: Automatic Theme Change
#  initial_state: 'off'
#  trigger:
#    - platform: homeassistant
#      event: start
#    - platform: state
#      entity_id: sun.sun
#      to: above_horizon
#    - platform: state
#      entity_id: sun.sun
#      to: below_horizon
#  action:
#    - service_template: frontend.set_theme
#      data_template:
#        name: >
#          {% if states.sun.sun.state == "above_horizon" %}
#            solarized_light
#          {% else %}
#            solarized_dark
#          {% endif %}
################################################################################

################################################################################
- id: weekly_backup
  alias: 'Weekly Backups'
  initial_state: 'on'
  trigger:
    platform: time
    at: '00:00:00'
  condition:
  - condition: time
    weekday:
      - mon
  action:
  - service: hassio.snapshot_full
    data_template:
      name: >
        {{ now().strftime('%Y%m%d') }} Weekly Backup
  - delay: '00:30'
  - service: hassio.addon_stdin
    data:
      addon: "7be23ff5_dropbox_sync"
      input:
        command: "upload"
################################################################################