- id: '1533651116446'
  alias: New Automation
  trigger:
  - entity_id: vacuum.roomba_downstairs
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - alias: ''
    data:
      message: Roomba Test Notification
    service: notify.notify
