### Device Trackers ###

# Automatic (Car Service)
- platform: automatic
  entity_namespace: obd
  client_id: !secret automatic_client_id
  secret: !secret automatic_secret
  username: !secret automatic_username
  password: !secret automatic_password
  devices:
    - 2018 Ford Escape

# UniFi
- platform: unifi
  entity_namespace: network
  host: !secret unifi_host
  port: !secret unifi_port
  username: !secret unifi_username
  password: !secret unifi_password
  site_id: default
  verify_ssl: false
  consider_home: 180
  new_device_defaults:
    track_new_devices: true
    hide_if_away: false

# OwnTracks
- platform: owntracks