---
title: Home
views:
- badges:
  - entity: person.ian
  - entity: person.aimee
  - entity: sensor.sagan
  - entity: sensor.hubble
  - entity: sensor.serenity
  cards:
  - cards:
    - entity: climate.homekit_downstairs
      type: thermostat
    - entity: climate.homekit_upstairs
      type: thermostat
    title: Thermostats
    type: horizontal-stack
  - columns: 2
    entities:
    - entity: light.master_bedroom_floor_lamp
    - entity: light.master_bedroom_table_lamps
    - entity: light.sitting_room_floor_lamp
    - entity: light.outdoor_garage_lights
    - entity: light.front_porch_lights
    - entity: light.dining_room_chandelier
    - entity: light.kitchen_chandelier
    - entity: light.kitchen_cabinet_lights
    - entity: light.master_bedroom_ceiling_fan
    - entity: light.living_room_ceiling_fan
    - entity: light.aimees_desk_lamp
    - entity: light.guest_bedroom_floor_lamp
    - entity: light.kitchen_pantry
    show_icon: true
    show_name: true
    show_state: false
    title: Lights
    type: glance
  - cards:
    - aspect_ratio: square
      camera_image: camera.upstairs_map
      entities:
      - entity: vacuum.upstairs
      image: http://upstairs-map:3000/api/map/image
      title: Upstairs
      type: picture-glance
    - aspect_ratio: square
      camera_image: camera.downstairs_map
      entities:
      - entity: vacuum.downstairs
      image: http://downstairs-map:3000/api/map/image
      title: Downstairs
      type: picture-glance
    title: Vacuums
    type: horizontal-stack
  - entities:
    - entity: sensor.template_downstairs_temperature
      index: 0
      name: Downstairs
    - entity: sensor.template_upstairs_temperature
      index: 1
      name: Upstairs
    - entity: sensor.homekit_kitchen_temperature
      index: 2
      name: Kitchen
    - entity: sensor.homekit_master_bedroom_temperature
      index: 3
      name: Master Bedroom
    name: Indoor Temperatures
    type: custom:mini-graph-card
  - entities:
    - entity: sun.sun
    - entity: sensor.moon
    - entity: sensor.garage_temperature
    show_icon: true
    show_name: true
    show_state: true
    title: Outside
    type: glance
  - dark_mode: false
    entities:
    - entity: person.aimee
    - entity: person.ian
    type: map
  - current: true
    details: true
    entity: weather.kfly_daynight
    type: custom:weather-card
  - entities:
    - entity: fan.living_room_ceiling_fan
    - entity: fan.master_bedroom_ceiling_fan
    show_header_toggle: false
    title: Fans
    type: entities
  icon: ''
  panel: false
  path: home
  title: Home
- badges: []
  cards:
  - entities:
    - entity: lock.front_door
    - entity: lock.back_door
    show_header_toggle: false
    theme: Backend-selected
    title: Locks
    type: entities
  - entities:
    - entity: binary_sensor.front_door
    - entity: binary_sensor.back_door
    - entity: binary_sensor.garage_door
    - entity: binary_sensor.living_room
    - entity: binary_sensor.glass_break
    type: glance
  - entities:
    - entity: input_datetime.alarm_auto_arm
    - entity: input_datetime.alarm_auto_disarm
    title: Alarm Settings
    type: entities
  - entity: alarm_control_panel.home
    states:
    - arm_home
    - arm_away
    type: alarm-panel
  - entities:
    - entity: alarm_control_panel.home
    - entity: cover.main_garage_door
    - entity: cover.second_garage_door
    type: glance
  - aspect_ratio: 0%
    entity: camera.xiaomicam
    name: Front Porch
    show_state: false
    type: picture-entity
  - aspect_ratio: 0%
    entity: camera.wyzecam
    name: Sagan's Crate
    show_state: false
    type: picture-entity
  path: security
  title: Security
- badges: []
  cards:
  - entity: media_player.master_bedroom_apple_tv
    type: media-control
  - entity: media_player.living_room_apple_tv
    type: media-control
  - entities:
    - entity: remote.living_room_apple_tv
    - entity: remote.master_bedroom_apple_tv
    title: Remotes
    type: entities
  path: media
  title: Media
- badges: []
  cards:
  - entities:
    - entity: automation.function_wakeup_bedroom_light
    - entity: automation.function_wakeup_apple_tv
    - entity: input_datetime.wakeup_time
    - entity: input_number.wakeup_duration
    - entity: input_select.alarm_type
    show_header_toggle: false
    title: Alarm Clock Settings
    type: entities
  - entities:
    - entity: sensor.next_sunrise
    - entity: input_datetime.morning
    - entity: input_number.morning_advance
    - entity: sensor.morning_start
    - entity: input_number.daytime_lighting_transition
    - entity: sensor.daytime_lighting_transition
    show_header_toggle: false
    title: Morning Settings
    type: entities
  - entities:
    - entity: sensor.next_sunset
    - entity: input_datetime.bedtime
    - entity: input_number.nighttime_delay
    - entity: sensor.nighttime_start
    - entity: input_number.nighttime_lighting_transition
    - entity: sensor.nighttime_lighting_transition
    show_header_toggle: false
    title: Night Time Settings
    type: entities
  - entities:
    - entity: input_boolean.away_mode
    - entity: input_boolean.vacation_ian
    - entity: input_boolean.vacation_aimee
    - entity: person.aimee
    - entity: person.ian
    show_header_toggle: false
    title: Presence
    type: entities
  path: settings
  title: Settings
- badges: []
  cards:
  - card:
      title: All Switches
      type: entities
    filter:
      include:
      - domain: switch
    sort:
      method: name
    type: custom:auto-entities
  - card:
      title: All Locks
      type: entities
    filter:
      include:
      - domain: lock
    sort:
      method: name
    type: custom:auto-entities
  - card:
      title: All Lights
      type: entities
    filter:
      include:
      - domain: light
    sort:
      method: name
    type: custom:auto-entities
  - card:
      title: All Remotes
      type: entities
    filter:
      include:
      - domain: remote
    sort:
      method: name
    type: custom:auto-entities
  - card:
      title: All Automations
      type: entities
    filter:
      include:
      - domain: automation
    sort:
      method: name
    type: custom:auto-entities
  - card:
      title: All Scripts
      type: entities
    filter:
      include:
      - domain: script
    sort:
      method: name
    type: custom:auto-entities
  - card:
      title: All Sensors
      type: entities
    filter:
      include:
      - domain: sensor
    sort:
      method: name
    type: custom:auto-entities
  - card:
      title: All Binary Sensors
      type: entities
    filter:
      include:
      - domain: binary_sensor
    sort:
      method: name
    type: custom:auto-entities
  - card:
      title: All Devices
      type: entities
    filter:
      include:
      - domain: device_tracker
    sort:
      method: name
    type: custom:auto-entities
  - card:
      title: All groups
      type: entities
    filter:
      include:
      - domain: group
    sort:
      method: name
    type: custom:auto-entities
  - card:
      title: All Input Numbers
      type: entities
    filter:
      include:
      - domain: input_number
    sort:
      method: name
    type: custom:auto-entities
  - card:
      title: All Input Booleans
      type: entities
    filter:
      include:
      - domain: input_boolean
    sort:
      method: name
    type: custom:auto-entities
  - card:
      title: All Input Date-Times
      type: entities
    filter:
      include:
      - domain: input_datetime
    sort:
      method: name
    type: custom:auto-entities
  panel: false
  path: everything
  title: Everything Else
- badges: []
  cards:
  - entity: sensor.us_coronavirus_confirmed
    graph: line
    type: sensor
  - entity: sensor.us_coronavirus_current
    graph: line
    theme: Backend-selected
    type: sensor
  - entity: sensor.us_coronavirus_deaths
    graph: line
    theme: Backend-selected
    type: sensor
  - entity: sensor.us_coronavirus_recovered
    graph: line
    theme: Backend-selected
    type: sensor
  - entities:
    - entity: sensor.us_coronavirus_confirmed
      index: 0
      name: Confirmed
    - entity: sensor.us_coronavirus_current
      index: 1
      name: Current
    - entity: sensor.us_coronavirus_recovered
      index: 2
      name: Recovered
    - entity: sensor.us_coronavirus_deaths
      index: 3
      name: Deaths
    name: US Coronavirus Totals
    type: custom:mini-graph-card
  - entities:
    - entity: sensor.worldwide_coronavirus_confirmed
      index: 0
      name: Confirmed
    - entity: sensor.worldwide_coronavirus_current
      index: 1
      name: Current
    - entity: sensor.worldwide_coronavirus_recovered
      index: 2
      name: Recovered
    - entity: sensor.worldwide_coronavirus_deaths
      index: 3
      name: Deaths
    name: Worldwide Coronavirus Totals
    type: custom:mini-graph-card
  icon: mdi:bottle-tonic-plus
  panel: false
  path: coronavirus
