resources:
  - url: /local/lovelace/custom/tracker-card.js
    type: js
  - url: /local/lovelace/custom/weather-card.js
    type: js
  - url: /local/lovelace/custom/monster-card.js
    type: js
  - url: /local/lovelace/custom/mini-graph-card-bundle.js
    type: js
  - url: /local/lovelace/custom/card-tools.js?track=true
    type: js
  - url: /local/lovelace/custom/auto-entities.js?track=true
    type: js
title: Percivale
views:
  - background: var(--background-image)
    badges: []
    cards:
      - type: glance
        title: Living Room
        entities:
          - entity: light.living_room_floor_lamp
            tap_action:
              action: toggle
          - entity: binary_sensor.living_room_motion
            name: Motion
          - entity: binary_sensor.back_door
      - entities:
          - entity: sensor.home_keypad
            name: Alarm
          - entity: lock.front_door
            name: Lock
          - entity: binary_sensor.front_door
          - entity: climate.downstairs
            name: Thermostat
        show_header_toggle: false
        title: Foyer
        type: glance
      - entities:
          - entity: light.dining_room
        show_header_toggle: false
        title: Dining Room
        type: entities
      - entities:
          - entity: light.kitchen_cabinet_lights
            name: Cabinet Lights
            tap_action:
              action: toggle
        show_header_toggle: false
        title: Kitchen
        type: glance
      - type: glance
        entities:
          - entity: lock.garage_door
            name: Garage Door
          - binary_sensor.garage_door
        show_header_toggle: false
        title: Garage
      - entities:
          - light.studio_floor_lamp
        show_header_toggle: false
        title: Studio
        type: entities
      - entities:
          - entity: light.master_bedroom_lights
            name: Floor Lamps
            tap_action:
              action: toggle
          - entity: switch.wink_overhead_light
            name: Overhead
            tap_action:
              action: toggle
          - entity: switch.wink_ceiling_fan
            tap_action:
              action: toggle
          - entity: sensor.wink_master_relay_temperature
            name: Temperature
        show_header_toggle: false
        title: Master Bedroom
        type: glance
      - entities:
          - entity: light.front_porch_lights
            tap_action:
              action: toggle
          - entity: binary_sensor.ring_front_door_motion
            name: Motion
          - entity: binary_sensor.ring_front_door_ding
            name: Doorbell
          - entity: sun.sun
          - entity: sensor.moon
        show_header_toggle: false
        title: Outside
        type: glance
      - entity: weather.dark_sky
        type: weather-forecast
      - entity: climate.downstairs
        type: thermostat
      - entities:
          - vacuum.roomba_upstairs
          - vacuum.roomba_downstairs
        show_header_toggle: false
        title: Roombas
        type: entities
      - entities:
          - entity: sensor.wink_master_relay_temperature
            name: Upstairs
          - entity: sensor.downstairs_thermostat_temperature
            name: Downstairs
        name: Temperature
        type: 'custom:mini-graph-card'
      - type: horizontal-stack
        title: Test Card
        cards:
          - type: light
            entity: light.kitchen_cabinet_lights
            name: Kitchen
          - type: light
            entity: light.dining_room
            name: Dining Room
    icon: ''
    panel: false
    path: home
    title: Home
  - background: var(--background-image)
    badges: []
    cards:
      - entity: media_player.master_bedroom_apple_tv
        type: media-control
      - entity: media_player.living_room_apple_tv
        type: media-control
    path: media
    title: Media
  - background: var(--background-image)
    badges: []
    cards:
      - entities:
          - sensor.home_keypad
          - binary_sensor.living_room_motion
          - binary_sensor.front_door
          - binary_sensor.back_door
          - binary_sensor.garage_door
        show_header_toggle: false
        title: Security System
        type: entities
      - entity: alarm_control_panel.home
        states:
          - arm_home
          - arm_away
        type: alarm-panel
      - entities:
          - entity: binary_sensor.ring_front_door_ding
          - entity: binary_sensor.ring_front_door_motion
          - entity: sensor.ring_front_door_last_activity
          - entity: sensor.ring_front_door_last_ding
          - entity: sensor.ring_front_door_last_motion
          - entity: camera.ring_front_door
        show_header_toggle: false
        title: Ring Doorbell
        type: entities
      - entities:
          - lock.front_door
          - lock.garage_door
        title: All Locks
        type: entities
    path: security
    title: Security
  - background: var(--background-image)
    badges: []
    cards:
      - entities:
          - entity: automation.function_wakeup_bedroom_light
          - entity: automation.function_wakeup_apple_tv
          - entity: input_datetime.wakeup_time
          - entity: input_number.wakeup_duration
        show_header_toggle: false
        title: Alarm Clock Settings
        type: entities
      - entities:
          - input_datetime.morning
          - input_number.morning_advance
          - sensor.morning_start
        show_header_toggle: false
        title: Morning Settings
        type: entities
      - entities:
          - input_datetime.bedtime
          - input_number.nighttime_delay
          - sensor.nighttime_start
        show_header_toggle: false
        title: Night Time Settings
        type: entities
      - entities:
          - input_boolean.vacation_ian
          - input_boolean.vacation_aimee
        title: Vacation
        type: entities
    path: settings
    title: Settings
  - background: var(--background-image)
    badges: []
    cards:
      - type: 'custom:auto-entities'
        card:
          title: All Switches
          type: entities
        filter:
          include:
            - domain: switch
      - type: 'custom:auto-entities'
        card:
          title: All Locks
          type: entities
        filter:
          include:
            - domain: lock
      - type: 'custom:auto-entities'
        card:
          title: All Lights
          type: entities
        filter:
          include:
            - domain: light
      - type: 'custom:auto-entities'
        card:
          title: All Remotes
          type: entities
        filter:
          include:
            - domain: remote
      - type: 'custom:auto-entities'
        card:
          title: All Automations
          type: entities
        filter:
          include:
            - domain: automation
      - type: 'custom:auto-entities'
        card:
          title: All Scripts
          type: entities
        filter:
          include:
            - domain: script
      - type: 'custom:auto-entities'
        card:
          title: All Sensors
          type: entities
        filter:
          include:
            - domain: sensor
      - type: 'custom:auto-entities'
        card:
          title: All Devices
          type: entities
        filter:
          include:
            - domain: device_tracker
    panel: false
    path: everything
    title: Everything Else
  - badges: []
    cards:
      - type: 'custom:tracker-card'
    icon: 'mdi:home-assistant'
    panel: true
    path: system
    title: System
