---
### Back Yard ###
automation:
  ################################################################################
  # Turn on the string lights around the back yard in the morning
  - id: area_back_yard_string_lights_morning
    alias: 'Area - Back Yard - String Lights (Morning)'
    triggers:
      - trigger: time
        at: input_datetime.morning
    conditions:
      condition: state
      entity_id: group.people
      state: 'home'
    actions:
      - alias: 'Turn on the back yard sting lights'
        action: light.turn_on
        target:
          entity_id: light.back_yard_string_lights
        data:
          brightness_pct: 50
  ################################################################################
  # Turn off the string lights around the back yard once the sun is up
  - id: area_back_yard_string_lights_dawn
    alias: 'Area - Back Yard - String Lights (Dawn)'
    triggers:
      - trigger: sun
        event: sunrise
        offset: '-00:15:00'
    conditions:
      condition: state
      entity_id: group.people
      state: 'home'
    actions:
      - alias: 'Ramp down lights over next 15 minutes'
        action: script.light_transition
        data:
          entity_id: light.back_yard_string_lights
          starting_brightness_pct: 50
          ending_brightness_pct: 0
          interval_pct: 5
          # TODO - Use template to determine time based upon weather conditions
          transition_time: 900
      - delay:
          seconds: 5
      - alias: 'Turn off the lights'
        action: light.turn_off
        target:
          entity_id: light.back_yard_string_lights
  ################################################################################
  # Turn on the string lights around the back yard when it gets dark
  - id: area_back_yard_string_lights_dusk
    alias: 'Area - Back Yard - String Lights (Dusk)'
    triggers:
      - trigger: sun
        event: sunset
    conditions:
      condition: state
      entity_id: group.people
      state: 'home'
    actions:
      - alias: 'Ramp up lights over next hour'
        action: script.light_transition
        data:
          entity_id: light.back_yard_string_lights
          starting_brightness_pct: 5
          ending_brightness_pct: 50
          interval_pct: 5
          # TODO - Use template to determine time based upon weather conditions
          transition_time: 3600
  ################################################################################
  # Turn off the string lights when the alarm is turned on
  # This is so that there is a clear indication that the alarm is on
  # and it's usually a good indication that I'm in bed or it's just late af.
  - id: area_back_yard_string_lights_night
    alias: 'Area - Back Yard - String Lights (Night)'
    triggers:
      - trigger: state
        entity_id:
          - alarm_control_panel.home
        to: 'armed_home'
    conditions:
      condition: state
      entity_id: group.people
      state: 'home'
    actions:
      - service: light.turn_off
        data:
          entity_id: light.back_yard_string_lights
  ################################################################################
  - id: area_back_yard_back_door_nfc
    alias: 'Area - Back Yard - Back Door NFC'
    triggers:
      platform: event
      event_type: tag_scanned
      event_data:
        tag_id: !secret nfc_back_door
    actions:
      - alias: 'State handler'
        choose:
          - conditions:
              - alias: 'Back Door Unlocked'
                condition: state
                entity_id: lock.back_door_lock
                state: 'unlocked'
            sequence:
              - alias: 'Lock Back Door'
                action: lock.lock
                target:
                  entity_id: lock.back_door_lock
          - conditions:
              - alias: 'Back Door Locked'
                condition: state
                entity_id: lock.back_door_lock
                state: 'locked'
            sequence:
              - alias: 'Unlock Back Door'
                action: lock.unlock
                target:
                  entity_id: lock.back_door_lock
################################################################################
