---
### Downstairs Bathroom ###

automation:
  ################################################################################
  - id: area_downstairs_bathroom_fan
    alias: Area - Downstairs Bathroom - Fan
    description: Turn on bathroom fan when motion is detected, turn off when no motion is detected
    triggers:
      - trigger: state
        entity_id: binary_sensor.downstairs_bathroom_motion_occupancy
    conditions:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'
    actions:
      - alias: State Handler
        choose:
          - conditions:
              - alias: Motion detected
                condition: state
                entity_id: binary_sensor.downstairs_bathroom_motion_occupancy
                state: 'on'
            sequence:
              - alias: Turn on the fan
                action: switch.turn_on
                target:
                  entity_id: switch.downstairs_bathroom_fan
          - conditions:
              - alias: Moton cleared
                condition: state
                entity_id: binary_sensor.downstairs_bathroom_motion_occupancy
                state: 'off'
            sequence:
              - alias: Turn off the fan
                action: switch.turn_off
                target:
                  entity_id: switch.downstairs_bathroom_fan
################################################################################
