---
### Downstairs ###
automation:
################################################################################
# Turn on the downstairs hallway lights when it gets dark
  - id: area_downstairs_hallway_lights_dusk
    alias: 'Area - Downstairs - Hallway Lights (Dusk)'
    trigger:
      - platform: sun
        event: sunset
    condition:
      - condition: state
        entity_id: group.people
        state: 'home'
    action:
      - service: light.turn_on
        data:
          entity_id: light.downstairs_hallway
          brightness_pct: 15
################################################################################