---
### Front Porch ###

automation:
  ################################################################################
  - id: area_front_porch_motion_initial
    alias: 'Area - Front Porch - Motion (Initial)'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_front_door
        from: 'off'
        to: 'on'
    condition:
      condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    action:
      # Transition to this profile, even if on
      - service: light.turn_on
        data:
          entity_id: light.front_porch_lights
          profile: energize
          brightness_pct: 100
          transition: 1
  ################################################################################
  - id: area_front_porch_motion_motion_idle
    alias: 'Area - Front Porch - Motion (Idle)'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_front_door
        from: 'on'
        to: 'off'
        for:
          seconds: 150
    condition:
      condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    action:
      # Transition back to a preset profile/scene
      - service: light.turn_on
        data:
          entity_id: light.front_porch_lights
          profile: relax
          brightness_pct: 50
          transition: 5
################################################################################
  - id: area_front_porch_front_door_nfc
    alias: 'Area - Front Porch - Front Door NFC'
    trigger:
      platform: event
      event_type: tag_scanned
      event_data:
        tag_id: !secret nfc_front_door
    action:
      - alias: "State handler"
        choose:
        - conditions:
          - alias: "Front Door Unlocked"
            condition: state
            entity_id: lock.front_door
            state: "unlocked"
          sequence:
          - alias: "Lock Front Door"
            service: lock.lock
            target:
              entity_id: lock.front_door
        - conditions:
          - alias: "Front Door Locked"
            condition: state
            entity_id: lock.front_door
            state: "locked"
          sequence:
          - alias: "Unlock Front Door"
            service: lock.unlock
            target:
              entity_id: lock.front_door
################################################################################
