---
### Front Porch ###

automation:
  ################################################################################
  - id: area_front_porch_motion_initial
    alias: 'Area - Front Porch - Motion (Initial)'
    triggers:
      - trigger: state
        entity_id: binary_sensor.front_door_camera_motion
        from: 'off'
        to: 'on'
    conditions:
      condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    actions:
      # Transition to this profile, even if on
      - service: light.turn_on
        data:
          entity_id: light.front_porch_lights
          profile: energize
          brightness_pct: 100
          transition: 1
  ################################################################################
  - id: area_front_porch_motion_motion_idle
    alias: 'Area - Front Porch - Motion (Idle)'
    triggers:
      - trigger: state
        entity_id: binary_sensor.front_door_camera_motion
        from: 'on'
        to: 'off'
        for:
          seconds: 150
    conditions:
      condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    actions:
      # Transition back to a preset profile/scene
      - service: light.turn_on
        data:
          entity_id: light.front_porch_lights
          profile: relax
          brightness_pct: 50
          transition: 5
  ################################################################################
  - id: area_front_porch_front_door_nfc
    alias: 'Area - Front Porch - Front Door NFC'
    triggers:
      platform: event
      event_type: tag_scanned
      event_data:
        tag_id: !secret nfc_front_door
    actions:
      - alias: 'State handler'
        choose:
          - conditions:
              - alias: 'Front Door Unlocked'
                condition: state
                entity_id: lock.front_door_lock
                state: 'unlocked'
            sequence:
              - alias: 'Lock Front Door'
                action: lock.lock
                target:
                  entity_id: lock.front_door_lock
          - conditions:
              - alias: 'Front Door Locked'
                condition: state
                entity_id: lock.front_door_lock
                state: 'locked'
            sequence:
              - alias: 'Unlock Front Door'
                action: lock.unlock
                target:
                  entity_id: lock.front_door_lock
################################################################################
