---
### Kitchen ###

input_number:
  ################################################################################
  dishwasher_energy_threshold:
    name: 'Dishwasher Energy Threshold'
    icon: mdi:lightning-bolt
    min: 0
    max: 100
    step: 5
    unit_of_measurement: Watts
################################################################################

binary_sensor:
  ################################################################################
  - platform: template
    sensors:
      dishwasher_status:
        friendly_name: 'Dishwasher Status'
        value_template: >
          {{ ( float(states.sensor.dishwasher_outlet_power.state)
            > float(states.input_number.dishwasher_energy_threshold.state) ) }}
################################################################################
automation:
  ################################################################################
  - id: area_kitchen_pantry_light
    alias: 'Area - Kitchen - Pantry Light'
    triggers:
      - trigger: state
        entity_id: binary_sensor.kitchen_pantry_door_contact
    actions:
      - alias: 'State Handler'
        choose:
          - conditions:
              - alias: 'Door is open'
                condition: state
                entity_id: binary_sensor.kitchen_pantry_door_contact
                state: 'on'
            sequence:
              action: light.turn_on
              data:
                entity_id: light.kitchen_pantry_light
                transition: 3
                brightness_pct: 100
          - conditions:
              - alias: 'Door is closed'
                condition: state
                entity_id: binary_sensor.kitchen_pantry_door_contact
                state: 'off'
            sequence:
              action: light.turn_off
              data:
                entity_id: light.kitchen_pantry_light
                transition: 1
################################################################################
