---
### Laundry Room ###

input_number:
  ################################################################################
  washing_machine_energy_threshold:
    name: 'Washing Machine Energy Threshold'
    icon: mdi:lightning-bolt
    min: 0
    max: 100
    step: 5
    unit_of_measurement: Watts
################################################################################

binary_sensor:
  ################################################################################
  - trigger: template
    sensors:
      dishwasher_status:
        friendly_name: 'Washing Machine Status'
        value_template: >
          {{ ( float(states.input_number.washing_machine_energy_threshold.state)
            < float(states.sensor.washing_machine_energy_usage.state) ) }}
        delay_off:
          minutes: 15
################################################################################
