---
### Laundry Room ###

input_number:
  ################################################################################
  washing_machine_energy_threshold:
    name: 'Washing Machine Energy Threshold'
    icon: mdi:lightning-bolt
    min: 0
    max: 100
    step: 5
    unit_of_measurement: Watts
################################################################################

binary_sensor:
  ################################################################################
  - platform: template
    sensors:
      washing_machine_status:
        friendly_name: 'Washing Machine Status'
        value_template: >
          {{ ( float(states.input_number.washing_machine_energy_threshold.state)
            < float(states.sensor.laundry_room_outlet_power.state) ) }}
        delay_off:
          minutes: 5
################################################################################

automation:
  ################################################################################
  - alias: 'Notify When Washing Machine Complete'
    description: 'Sends a notification when the washing machine finishes its cycle'
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_machine_status
        from: 'on'
        to: 'off'
    action:
      - service: notify.notify
        data:
          title: 'Laundry Alert'
          message: 'The washing machine has finished its cycle! 🧺'
          data:
            push:
              sound:
                name: 'default'
                critical: 1
                volume: 1.0

  - alias: 'Notify When Dryer Complete'
    description: 'Sends a notification when the dryer stops vibrating'
    trigger:
      - platform: state
        entity_id: binary_sensor.dryer_vibration_sensor_vibration
        from: 'on'
        to: 'off'
        for:
          minutes: 2
    action:
      - service: notify.notify
        data:
          title: 'Laundry Alert'
          message: 'The dryer has finished its cycle! 👕'
          data:
            push:
              sound:
                name: 'default'
                critical: 1
                volume: 1.0

  - alias: 'Reset Laundry Notifications'
    description: 'Reset notification state when machines start again'
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_machine_status
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.dryer_vibration_sensor_vibration
        from: 'off'
        to: 'on'
    action:
      - service: persistent_notification.dismiss
        data:
          notification_id: laundry_notification
          ################################################################################
