---
### Living Room ###
automation:
  ################################################################################
  # Turn on the living room light when it gets dark
  - id: area_living_room_ceiling_fan_light_dusk
    alias: 'Area - Living Room - Ceiling Fan Light (Dusk)'
    triggers:
      - trigger: sun
        event: sunset
    conditions:
      - condition: and
        conditions:
          - condition: state
            entity_id: group.people
            state: 'home'
            # Because this light is controlled via an RF interface, the actual
            # state of the light is unknown. However, by checking the HA state
            # we can try to mitigate the physical state getting flipped.
          - condition: state
            entity_id: light.living_room_ceiling_fan
            state: 'off'
    actions:
      - action: light.turn_on
        data:
          entity_id: light.living_room_ceiling_fan
  ################################################################################
  # Turn off the string lights when the alarm is turned on
  # This is so that there is a clear indication that the alarm is on
  - id: area_living_room_ceiling_fan_light_night
    alias: 'Area - Living Room - Ceiling Fan Light (Night)'
    triggers:
      - trigger: state
        entity_id:
          - alarm_control_panel.home
        to: 'armed_home'
    conditions:
      - condition: and
        conditions:
          - condition: state
            entity_id: group.people
            state: 'home'
          - condition: state
            entity_id: light.living_room_ceiling_fan
            state: 'on'
    actions:
      # Wait a few minutes before shutting the light off in case we're still up.
      - delay:
          minutes: 5
      - action: light.turn_off
        data:
          entity_id: light.living_room_ceiling_fan
  ################################################################################
  # Automatically turn the fireplace blower on when the fireplace is turned on
  # and leave the blower on for 30 minutes after the fireplace has been turned off
  # to allow the fireplace to cool down.
  - id: area_living_room_fireplace_blower
    alias: 'Area - Living Room - Fireplace Blower'
    triggers:
      # Specifying specific state changes from on <-> off because the shelly
      # that's installed here keeps going 'unavailable' and triggering this.
      - trigger: state
        entity_id:
          - switch.fireplace
        to: 'on'
        from: 'off'
      - trigger: state
        entity_id:
          - switch.fireplace
        to: 'off'
        from: 'on'
    actions:
      - choose:
          - conditions:
              - condition: state
                entity_id:
                  - switch.fireplace
                state: 'on'
            sequence:
              - action: switch.turn_on
                entity_id: switch.fireplace_blower
          - conditions:
              - condition: state
                entity_id:
                  - switch.fireplace
                state: 'off'
            sequence:
              - delay:
                  minutes: 30
              - condition: state
                entity_id: switch.fireplace
                state: 'off'
              - action: switch.turn_off
                entity_id: switch.fireplace_blower
  # In case anyone is looking at this and is curious how I set this up:
  # The fireplace is a pretty typical millivolt valve being controlled by a Shelly
  # and the blower switch is just an Inovelli LZW30-SN.
  ################################################################################
  # Toggle Hyperion power with TV state
  - id: area_living_room_hyperion_power
    alias: 'Area - Living Room - Hyperion Power'
    triggers:
      - trigger: state
        entity_id: media_player.living_room_tv
        to:
          - 'on'
          - 'off'
    actions:
      - choose:
          - conditions:
              - condition: state
                entity_id: media_player.living_room_tv
                state: 'on'
            sequence:
              - action: switch.turn_on
                target:
                  entity_id: group.hyperion_led_outputs
          - conditions:
              - condition: state
                entity_id: media_player.living_room_tv
                state: 'off'
            sequence:
              - action: switch.turn_off
                target:
                  entity_id: group.hyperion_led_outputs
