---
### Master Bedroom ###

# Inputs
input_number:
  master_bedroom_humidifer_threshold:
    name: "Master Bedroom Humidier Threshold"
    min: 0
    max: 100
    step: 10

# Template Sensors
sensor:
  - platform: template
    sensors:
      master_bedroom_humidifer_level:
        friendly_name: "Master Bedroom Humidier Level"
        value_template: >
          {{ state_attr('fan.master_bedroom_humidifier', 'depth') | int }}
      master_bedroom_humidifer_low:
        friendly_name: "Master Bedroom Humidier Low"
        value_template: >
          {{ ( float(states.sensor.master_bedroom_humidifer_level.state) > 
          float(states.input_number.master_bedroom_humidifer_threshold.state) ) }}

# Alerts
alert:
  master_bedroom_humidifer_low:
    name: Master Bedroom Humidier Low
    entity_id: binary_sensor.master_bedroom_humidifer_low
    state: "on"
    repeat: 120
    can_acknowledge: true
    notifiers:
      - ians_iphone

# Automations
automation:
################################################################################
- id: area_master_bedroom_closet_motion
  alias: Area - Master Bedroom - Closet Motion
  trigger:
  - platform: state
    entity_id: binary_sensor.master_bedroom_closet_motion
  condition:
  - alias: "House is occupied"
    condition: state
    entity_id: group.people
    state: "home"
  action:
  - alias: "Status handler"
    choose:
    - conditions:
      - alias: "Motion detected"
        condition: state
        entity_id: binary_sensor.master_bedroom_closet_motion
        state: "on"
      sequence:
      - alias: "Turn on closet light"
        service: light.turn_on
        target:
          entity_id: light.master_bedroom_closet
    - conditions:
      - alias: "Motion cleared"
        condition: state
        entity_id: binary_sensor.master_bedroom_closet_motion
        state: "off"
      sequence:
      - alias: "Turn off closet light"
        service: light.turn_off
        target:
          entity_id: light.master_bedroom_closet
################################################################################
