---
### Master Bathroom ###

# Inputs
input_number:
  # This will be used for the shower automation
  master_bathroom_humidity_threshold:
    name: Master Bathroom Humidity Threshold
    icon: mdi:water-percent
    min: 0
    max: 100
    step: 5
    unit_of_measurement: Percent

binary_sensor:
  - platform: template
    sensors:
      master_bathroom_humidity_high:
        friendly_name: "Master Bathroom Humidity High"
        value_template: >
          {{ ( float(states.input_number.master_bathroom_humidity_threshold.state)
            < float(states.sensor.master_bathroom_humidity.state) ) }}

# Automations
automation:
################################################################################
# Turn on the fan when someone is in the shower. 
  - id: function_master_bathroom_humidity_high
    alias: 'Function - Master Bathroom - Humidity High'
    trigger:
      platform: state
      entity_id:
        - binary_sensor.master_bathroom_humidity_high
      from: "off"
      to: "on"
      for: 
        seconds: 10
    action:
      - service: switch.turn_on
        data:
          entity_id: switch.master_bathroom_fan
################################################################################
  - id: function_master_bathroom_humidity_low
    alias: 'Function - Master Bathroom - Humidity Low'
    trigger:
      platform: state
      entity_id:
        - binary_sensor.master_bathroom_humidity_high
      from: "on"
      to: "off"
      for:
        seconds: 10
    condition:
    # Only execute if the toilet door is already open
      condition: state
      entity_id:
        - binary_sensor.master_bathroom_toilet_door
      state: 'on'
    action:
      - delay:
          minutes: 5
      - service: switch.turn_off
        data:
          entity_id: switch.master_bathroom_fan
################################################################################
# Turn on the fan when the shitter closet door is closed.
  - id: function_master_bathroom_toilet_door_closed
    alias: 'Function - Master Bathroom - Toilet Door Closed'
    trigger:
      platform: state
      entity_id:
        - binary_sensor.master_bathroom_toilet_door
      from: "on"
      to: "off"
      for:
        seconds: 10
    action:
      - service: switch.turn_on
        data:
          entity_id: switch.master_bathroom_fan
################################################################################
  - id: function_master_bathroom_toilet_door_open
    alias: 'Function - Master Bathroom - Toilet Door Open'
    trigger:
      platform: state
      entity_id:
        - binary_sensor.master_bathroom_toilet_door
      from: "off"
      to: "on"
      for:
        seconds: 10
    condition:
      # Only execute if someone isn't in the shower
      condition: state
      entity_id:
        - binary_sensor.master_bathroom_humidity_high
      state: 'off'
    action:
      - delay:
          minutes: 5
      - service: switch.turn_off
        data:
          entity_id: switch.master_bathroom_fan
################################################################################