---
### Master Bedroom ###

# Inputs
input_number:
  master_bedroom_humidifer_threshold:
    name: 'Master Bedroom Humidier Threshold'
    min: 0
    max: 100
    step: 10

# Template Sensors
binary_sensor:
  - platform: template
    sensors:
      master_bedroom_humidifer_low:
        friendly_name: 'Master Bedroom Humidier Low'
        value_template: >
          {{ ( float(states('sensor.master_bedroom_humidifier_water_level')) <
          float(states('input_number.master_bedroom_humidifer_threshold')) ) }}

# Alerts
alert:
  master_bedroom_humidifer_low:
    name: Master Bedroom Humidier Low
    entity_id: binary_sensor.master_bedroom_humidifer_low
    message: 'Go refil the master bedroom humidifier'
    done_message: 'Was that so hard?'
    state: 'on'
    repeat: 120
    can_acknowledge: true
    notifiers:
      - ians_iphone
      - mobile_app_iphone

# Automations
automation:
  ################################################################################
  - id: area_master_bedroom_closet_motion
    alias: Area - Master Bedroom - Closet Motion
    triggers:
      - trigger: state
        entity_id: binary_sensor.master_bedroom_closet_motion_occupancy
    conditions:
      - alias: 'House is occupied'
        condition: state
        entity_id: group.people
        state: 'home'
    actions:
      - alias: 'Status handler'
        choose:
          - conditions:
              - alias: 'Motion detected'
                condition: state
                entity_id: binary_sensor.master_bedroom_closet_motion_occupancy
                state: 'on'
            sequence:
              - alias: 'Turn on closet light'
                action: light.turn_on
                target:
                  entity_id: light.master_bedroom_closet_light
          - conditions:
              - alias: 'Motion cleared'
                condition: state
                entity_id: binary_sensor.master_bedroom_closet_motion_occupancy
                state: 'off'
            sequence:
              - alias: 'Turn off closet light'
                action: light.turn_off
                target:
                  entity_id: light.master_bedroom_closet_light
  ################################################################################
  - id: area_master_bedroom_panic_button
    alias: Area - Master Bedroom - Panic Button
    triggers:
      - trigger: event
        event_type: zha_event
        event_data:
          unique_id: !secret panic_button_unique_id
          args:
            attribute_name: on_off
            # Upon release
            value: 1
    # condition:
    actions:
      # - alias: "Test"
      #   service: notify.alexa_media
      #   data:
      #     data:
      #       type: tts
      #     target:
      #       - media_player.downstairs_thermostat
      #       - media_player.upstairs_thermostat
      #     message: 'The button was pressed.'
      - alias: 'Sound the alarm'
        action: alarm_control_panel.alarm_trigger
        data:
          entity_id: alarm_control_panel.home
          code: !secret alarm_code
  ################################################################################
  - id: area_master_bedroom_bedjet_preconditioning
    alias: Area - Master Bedroom - BedJet Preconditioning
    triggers:
      - trigger: time
        at: input_datetime.bedtime
    conditions:
      - alias: 'House is occupied'
        condition: state
        entity_id: group.people
        state: 'home'
    actions:
      - alias: 'Get overnight low temperature'
        variables:
          overnight_low: >
            {{ state_attr('weather.pirate_weather', 'forecast')[0].templow | float }}
      - alias: 'Set BedJet based on conditions'
        choose:
          - conditions:
              - alias: 'Very cold night - extended heat'
                condition: template
                value_template: '{{ overnight_low < 0 }}'
            sequence:
              - alias: 'Set extended heat preset'
                action: climate.set_preset_mode
                target:
                  entity_id: climate.ians_bedjet
                data:
                  preset_mode: extended heat
          - conditions:
              - alias: 'Cold night - pre-heat the bed'
                condition: template
                value_template: '{{ overnight_low < 10 }}'
            sequence:
              - alias: 'Heat the bed to 25°C'
                action: climate.set_temperature
                target:
                  entity_id: climate.ians_bedjet
                data:
                  temperature: 25
                  hvac_mode: heat
          - conditions:
              - alias: 'Warm night - pre-cool the bed'
                condition: template
                value_template: '{{ overnight_low > 25 }}'
            sequence:
              - alias: 'Cool the bed to 15°C'
                action: climate.set_temperature
                target:
                  entity_id: climate.ians_bedjet
                data:
                  temperature: 15
                  hvac_mode: cool
          - conditions:
              - alias: 'Room is warm but moderate night - just use fan'
                condition: numeric_state
                entity_id: sensor.ians_bedjet_ambient_temperature
                above: 25
            sequence:
              - alias: 'Turn on BedJet fan'
                action: fan.turn_on
                target:
                  entity_id: fan.ians_bedjet
        default:
          - alias: 'Moderate temperature - turn off BedJet'
            action: climate.turn_off
            target:
              entity_id: climate.ians_bedjet
################################################################################
