---
### Office ###

light:
  ################################################################################
  - trigger: group
    name: Office Stream Lights
    unique_id: office_stream_lights
    entities:
      - light.office_panel_lights_south
      - light.office_panel_lights_west
      - light.office_workbench_lights
  - trigger: group
    name: Office Camera Lights
    unique_id: office_camera_lights
    entities:
      - light.office_fill_light
      - light.office_key_light
################################################################################

automation:
  ################################################################################
  - alias: Area - Office - Workbench Button Click
    triggers:
      - trigger: state
        entity_id: sensor.office_workbench_button_action
        to: 'on'
    actions:
      entity_id: light.office_workbench_lights
      action: light.toggle
################################################################################
