---
### Office ###
automation:
  ################################################################################
  - alias: Area - Office - Workbench Button Click
    trigger:
      - platform: state
        entity_id: sensor.office_workbench_button_action
        to: 'on'
    action:
      entity_id: light.office_workbench_lights
      service: light.toggle
################################################################################
