---
### Office ###
automation:
################################################################################
# Turn on the office floor lamp when it gets dark
  - id: area_office_floor_lamp_dusk
    alias: 'Area - Office - Floor Lamp (Dusk)'
    trigger:
      - platform: sun
        event: sunset
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: person.ian
            state: 'home'
    action:
      - service: light.turn_on
        data:
          entity_id: light.office_floor_lamp
################################################################################