---
### Upstairs ###
automation:
################################################################################
# Turn on the upstairs hallway lights when it gets dark
  - id: area_upstairs_hallway_lights_dusk
    alias: 'Area - Upstairs - Hallway Lights (Dusk)'
    trigger:
      - platform: sun
        event: sunset
    condition:
      - condition: state
        entity_id: group.people
        state: 'home'
    action:
      - service: light.turn_on
        data:
          entity_id: light.upstairs_hallway
          brightness_pct: 15
################################################################################