### Presence Detection Functionality ###

group:
################################################################################
  vacation_settings:
    name: Vacation
    control: hidden
    entities:
      - input_boolean.vacation_ian
      - input_boolean.vacation_aimee
################################################################################
  network_phones:
    name: Phones
    entities:
      - device_tracker.network_aimees_iphone
      - device_tracker.network_ians_iphone
################################################################################
  people:
    name: People
    entities:
      - person.ian
      - person.aimee
################################################################################

# The Bayesian sensor has been a real bitch to wrap my head around.
# One extremely valuable resource has been robmarkcole's Jupityr notebook.
# http://nbviewer.jupyter.org/github/robmarkcole/HASS-data-science/blob/master/Bayesian%20sensor%20tutorial.ipynb

binary_sensor:
################################################################################
  - platform: bayesian
    prior: 0.00 # The initial probability that the house is empty
    name: 'Occupancy'
    probability_threshold: 0.5
    observations:
      - entity_id: person.ian
        prob_given_true: 1.0
        prob_given_false: 0.0
        platform: 'state'
        to_state: 'home'
      - entity_id: person.aimee
        prob_given_true: 1.0
        prob_given_false: 0.0
        platform: 'state'
        to_state: 'home'
################################################################################

input_boolean:
################################################################################
  vacation_ian:
    name: 'Vacation - Ian'
    initial: off
    icon: mdi:beach
  vacation_aimee:
    name: 'Vacation - Aimee'
    initial: off
    icon: mdi:beach
################################################################################

automation:
################################################################################
  - id: function_presence_detection
    alias: "Function - Presence Detection"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: group.people
    action:
      service_template: >
        {% if is_state('group.people', 'home') %}
          script.location_home
        {% elif is_state('group.people', 'not_home') %}
          script.location_away
        {% endif %}
################################################################################
  - id: function_vacation_detection
    alias: "Function - Vacation Detection"
    initial_state: 'off'
    trigger:
      - platform: state
        entity_id: group.people
    action:
      service_template: >
        # TODO - If location > 100km from home, set vacation input_boolean
        {% if is_state('group.people', 'home') %}
          script.location_home
        {% elif is_state('group.people', 'not_home') %}
          script.location_away
        {% endif %}
################################################################################
  - id: test_person
    alias: "Test - Person Component"
    initial_state: 'off'
    trigger:
      - platform: state
        entity_id: 
        - person.ian
        - person.aimee
    action:
      - service: notify.notify
        data:
          message: >
            Person Component Triggered: {{ trigger.entity_id }} 
################################################################################

scene:
################################################################################
  - name: Home
    entities:
      alarm_control_panel.home: 'disarmed'
      climate.downstairs: 'home'
################################################################################

################################################################################
  - name: Away
    entities:
      alarm_control_panel.home: 'armed_away'
      climate.downstairs: 'away'
################################################################################

# Scripts
script:
################################################################################
  location_away:
    alias: 'Function - Presence - Away'
    sequence:
      # Turn off all of the lights
      - service: light.turn_off
        data:
          entity_id: group.indoor_lights
      # Turn the thermostat off
      - service: nest.set_away_mode
        data:
          away_mode: away
      # Arm the alarm
      - service: alarm_control_panel.alarm_arm_away
        data:
          entity_id: alarm_control_panel.home
          code: !secret alarm_code
      # Randomly turn on and off lights to simulate occupancy
      # TODO
################################################################################
  location_home:
    alias: 'Function - Presence - Home'
    sequence:
      # Turn everything back on (Call scene)
      # Turn the thermostat back on
      - service: nest.set_away_mode
        data:
          away_mode: home
      # Disarm the alarm
      - service: alarm_control_panel.alarm_disarm
        data:
          entity_id: alarm_control_panel.home
          code: !secret alarm_code
################################################################################
