### System Notifications ###

automation:
################################################################################
- id: system_notification_update
  alias: 'System - Notification - Update Available'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: updater.updater
# TODO: Condition on verified config
#  homeassistant check = 'ok'
#  condition:
#    condition: template
#    value_template: >
#      {{ true }}
  action:
    service: notify.notify
    data:
      message: 'An update for Home Assistant is available.'
################################################################################

################################################################################
- id: system_notification_new_device
  alias: 'System - Notification - New Device'
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: device_tracker_new_device
  action:
    - service: notify.notify
      data_template:
        message: >
          Home Assistant has discovered a new device:
          {{trigger.event.data.entity_id}}
        title: New Device
################################################################################

################################################################################
- id: system_notification_restart
  alias: 'System - Notification - Home Assistant Restart'
  initial_state: 'on'
  trigger:
    platform: homeassistant
    event: start
  action:
    service: notify.notify
    data:
      message: 'Home Assistant has restarted.'
################################################################################

################################################################################
- id: system_notification_certification_expiration
  alias: 'System - Notification - Home Assistant Certificate'
  initial_state: 'on'
  trigger:
    platform: template
    value_template: >
      {{ states.sensor.ssl_certificate_expiry.state | int  <= 14 }}
  condition:
    condition: template
    value_template: >
      {{ states.sensor.ssl_certificate_expiry.state != "unknown" }}
  action:
    service: notify.notify
    data_template:
      message: >
        Home Assistant's certificate expires in {{ states.sensor.ssl_certificate_expiry.state }} days.
################################################################################

################################################################################
#  # IF: { sun.sun goes under horizon } THEN: { set theme to night mode }
#- id: theme_automatic
#  alias: Automatic Theme Change
#  initial_state: 'off'
#  trigger:
#    - platform: homeassistant
#      event: start
#    - platform: state
#      entity_id: sun.sun
#      to: above_horizon
#    - platform: state
#      entity_id: sun.sun
#      to: below_horizon
#  action:
#    - service_template: frontend.set_theme
#      data_template:
#        name: >
#          {% if states.sun.sun.state == "above_horizon" %}
#            solarized_light
#          {% else %}
#            solarized_dark
#          {% endif %}
################################################################################