### System Backups ###

automation:
################################################################################
- id: system_backup_weekly
  alias: 'System - Backup - Weekly'
  initial_state: 'off'
  trigger:
    platform: time
    at: '00:00:00'
  condition:
  - condition: time
    weekday:
      - mon
  action:
  - service: hassio.snapshot_full
    data_template:
      name: >
        {{ now().strftime('%Y%m%d') }} Weekly Backup
# Leaving this here for now. I need to get this working via rsync or something
#  - delay: '00:30'
#  - service: hassio.addon_stdin
#    data:
#      addon: "7be23ff5_dropbox_sync"
#      input:
#        command: "upload"
################################################################################