### System Backups ###

# The following configuration is dependent upon jcwillox's hass-auto-backup 
# integration (installed via HACS) https://github.com/jcwillox/hass-auto-backup

auto_backup:
  auto_purge: true

# The following automations are adapted from jcwillox's documentation
# https://github.com/jcwillox/hass-auto-backup#automation

automation:
################################################################################
- id: system_backup_partial
  alias: 'System - Backup - Partial'
  trigger:
    # Perform backup every 6 hours.
    platform: time_pattern
    hours: "/6"
  action:
    # Only perform a partial snapshot to save storage.
    service: auto_backup.snapshot_partial
    data_template:
      name: "Partial Backup: {{ now().strftime('%a, %-I:%M %p (%d/%m/%Y)') }}"
      addons:
        # It doesn't matter if you use the addon slug or name. Name is easier.
        - core_mariadb 
        - a0d7b954_mqtt
      folders:
        - homeassistant
        - share
        - ssl
      keep_days: 2
################################################################################
- id: system_backup_daily
  alias: 'System - Backup - Daily'
  trigger:
    platform: time
    at: "02:30:00"
  condition:
    condition: time # Perform backup every day except Mondays.
    weekday:
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
  action:
    service: auto_backup.snapshot_full
    data_template:
      name: "Daily Backup: {{ now().strftime('%A, %B %-d, %Y') }}"
      keep_days: 7
    ### TODO: Backups need to be shipped off to an external storage location ###
    ### https://github.com/jcwillox/hass-auto-backup#backup-path maybe? ###
################################################################################
- id: system_backup_weekly
  alias: 'System - Backup - Weekly'
  trigger:
    platform: time
    at: "02:30:00"
  condition:
    condition: time # On Mondays perform a weekly backup
    weekday:
      - mon
  action:
    service: auto_backup.snapshot_full
    data_template:
      name: "Weekly Backup: {{ now().strftime('%A, %B %-d, %Y') }}"
      # Store backup for a month, basically perform 1 backup each week and 
      # store for 4 weeks.
      keep_days: 28 
################################################################################
- id: system_backup_failure
  alias: "System - Backup - Notification (Failure)"
  trigger:
    platform: event
    event_type: auto_backup.snapshot_failed
  action:
    service: persistent_notification.create
    data_template:
      title: "Snapshot Failed."
      message: "Name: {{ trigger.event.data.name }}\nError: {{ trigger.event.data.error }}"
################################################################################

# The following automation is now deprecated. Will be purged at a later date
################################################################################
# - id: system_backup_weekly
#   alias: 'System - Backup - Weekly'
#   initial_state: 'off'
#   trigger:
#     platform: time
#     at: '00:00:00'
#   condition:
#   - condition: time
#     weekday:
#       - mon
#   action:
#   - service: hassio.snapshot_full
#     data_template:
#       name: >
#         {{ now().strftime('%Y%m%d') }} Weekly Backup
# Leaving this here for now. I need to get this working via rsync or something
#  - delay: '00:30'
#  - service: hassio.addon_stdin
#    data:
#      addon: "7be23ff5_dropbox_sync"
#      input:
#        command: "upload"
################################################################################