# This configuration file will define multiple Xiaomi devices including
# - Roborock Vacuums
# - Aquara Devices

vacuum:
  - platform: xiaomi_miio
    name: Downstairs Vacuum
    entity_id: downstairs_vacuum
    host: !secret downstairs_vacuum_host
    token: !secret downstairs_vacuum_token


switch:
################################################################################
  - platform: template
    switches:
# Downstairs Vacuum
      vacuum_downstairs:
        friendly_name: "Downstairs Vacuum"
        value_template: "{{ is_state('vacuum.downstairs_vacuum', 'on') }}"
        turn_on:
          service: 'vacuum.start'
          data:
            entity_id: 'vacuum.downstairs_vacuum'
        turn_off: 
          service: 'vacuum.stop'
          data:
            entity_id: 'vacuum.downstairs_vacuum'
        icon_template: >-
          {% if is_state('vacuum.downstairs_vacuum', 'on') %}
            mdi:broom
          {% else %}
            mdi:robot-vacuum
          {% endif %}
################################################################################

automation:
################################################################################
# keep the vacuum going if it complains that it's stuck.
# We have fairly high pile carpets, and the added resistance against the 
# brush is typically percieved as something being caught in the brush.
# To work around this, we just tell the vacuum to keep going.
  - id: function_vacuum_restart
    alias: "Function - Vacuum - Restart"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:
          - vacuum.downstairs_vacuum
          - vacuum.upstairs_vacuum
        from: cleaning
        to: error
    action:
      - delay: 0:30
      - service: 'vacuum.start'
        data:
          entity_id: "{{ trigger.entity_id }}"

################################################################################
# While we're out of the house, keep sending the vacuum out as soon as it's
# reached a full charge. This may or may not end well.
  - id: function_vacuum_continue
    alias: "Function - Vacuum - Continue"
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id:
          - vacuum.downstairs_vacuum
          - vacuum.upstairs_vacuum
        value_template: "{{ state.attributes.battery }}"
        above: 99
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.away_mode
          state: 'on'
        - condition: state
          entity_id: "{{ trigger.entity_id }}"
          state:  docked
    action:
      - delay: 0:30
      - service: 'vacuum.start'
        data:
          entity_id: "{{ trigger.entity_id }}"
################################################################################