# Roborock Vacuums

# The vacuums are rooted and running Valetudo-RE for granular local control and
# separation from the Xiaomi cloud. Plus, I can get the maps in lovelace.
# I've used the mirobo tool to upload firmware built by vacuumz.info
# mirobo --ip 192.168.8.1 --token $$$ update-firmware ~/Downloads/root_1886.pkg
# Vacuumz.info - https://vacuumz.info/download/gen2/stock_root/
# mirobo - https://github.com/rytilahti/python-miio
# ValetudoRE - https://github.com/rand256/Valetudo/

vacuum:
  - platform: xiaomi_miio
    name: Downstairs Vacuum
    entity_id: downstairs_vacuum
    host: !secret downstairs_vacuum_host
    token: !secret downstairs_vacuum_token
    
  - platform: xiaomi_miio
    name: Upstairs Vacuum
    entity_id: upstairs_vacuum
    host: !secret upstairs_vacuum_host
    token: !secret upstairs_vacuum_token

# Both of these devices are also being populated in Home Assistant
# via MQTT auto-discovery, which I may or may not utilize in the future.
# I like that the miio protocol does not rely on an MQTT broker.
# The devices get populated as 'vacuum.downstairs' & 'vacuum.upstairs'
# which is a little less redundant than 'vacuum.downstairs_vacuum' etc.
# I don't know how I'll proceed. I'm just making notes for future me.

switch:
################################################################################
  - platform: template
    switches:
# Downstairs Vacuum
      vacuum_downstairs:
        friendly_name: "Downstairs Vacuum"
        value_template: "{{ is_state('vacuum.downstairs_vacuum', 'on') }}"
        turn_on:
          service: 'vacuum.start'
          data:
            entity_id: 'vacuum.downstairs_vacuum'
        turn_off: 
          service: 'vacuum.stop'
          data:
            entity_id: 'vacuum.downstairs_vacuum'
        icon_template: >-
          {% if is_state('vacuum.downstairs_vacuum', 'on') %}
            mdi:broom
          {% else %}
            mdi:robot-vacuum
          {% endif %}
################################################################################

automation:
################################################################################
# keep the vacuum going if it complains that it's stuck.
# We have fairly high pile carpets, and the added resistance against the 
# brush is typically percieved as something being caught in the brush.
# To work around this, we just tell the vacuum to keep going.
  - id: function_vacuum_restart
    alias: "Function - Vacuum - Restart"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:
          - vacuum.downstairs_vacuum
          - vacuum.upstairs_vacuum
        from: cleaning
        to: error
    action:
      - delay: 0:30
      - service: 'vacuum.start'
        data:
          entity_id: "{{ trigger.entity_id }}"

################################################################################
# While we're out of the house, keep sending the vacuum out as soon as it's
# reached a full charge. This may or may not end well.
  - id: function_vacuum_continue
    alias: "Function - Vacuum - Continue"
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id:
          - vacuum.downstairs_vacuum
          - vacuum.upstairs_vacuum
        value_template: "{{ state.attributes.battery }}"
        above: 99
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.away_mode
          state: 'on'
        - condition: template
          value_template: "{{ trigger.entity_id }} = docked"
    action:
      - delay: 0:30
      - service: 'vacuum.start'
        data:
          entity_id: "{{ trigger.entity_id }}"
################################################################################