---
### Astronomy Automations ###

automation:
################################################################################
  ## Send a notification on new moon nights
  - id: routine_astronomy_dark_sky
    alias: 'Routine - Astronomy - Dark Sky'
    # initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sun.sun
        from: 'above_horizon'
        to: 'below_horizon'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sensor.moon
          state: 'new_moon'
        - condition: state
          entity_id: sensor.dark_sky_summary
          state: 'Clear'
    action:
      - service: notify.notify
        data:
          message: 'New moon tonight.'
################################################################################
  ## Send a notification on full moon nights
  - id: routine_astronomy_lunar
    alias: 'Routine - Astronomy - Dark Sky'
    # initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sun.sun
        from: 'above_horizon'
        to: 'below_horizon'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sensor.moon
          state: 'full_moon'
        - condition: state
          entity_id: sensor.dark_sky_summary
          state: 'Clear'
    action:
      - service: notify.notify
        data:
          message: 'Full moon tonight.'
################################################################################