---
### Daytime Routines ###

################################################################################
# Inputs
################################################################################
input_datetime:
  morning:
    name: Morning
    has_date: false
    has_time: true
    # initial: '05:00'

input_number:
  morning_advance:
    name: Morning Advance
    icon: mdi:clock-in
    # initial: 60
    min: 0
    max: 120
    step: 15
    unit_of_measurement: Minutes

  daytime_lighting_transition:
    name: Day Time Lighting Transition
    icon: mdi:clock-in
    # initial: 15
    min: 0
    max: 30
    step: 5
    unit_of_measurement: Minutes
################################################################################

template:
  ################################################################################
  - sensor:
      - default_entity_id: sensor.morning
        name: Morning
        icon: mdi:clock-outline
        state: >
          {{ states.input_datetime.morning.attributes.timestamp |
              int | timestamp_custom("%H:%M",False) }}
      - default_entity_id: sensor.morning_start
        name: Morning Start
        icon: mdi:clock-outline
        state: >
          {{ (((states.input_datetime.morning.attributes.timestamp |
              int) - (states.input_number.morning_advance.state |
              int * 60)) | timestamp_custom("%H:%M",False)) }}
      - default_entity_id: sensor.daytime_lighting_transition
        name: Day Time Lighting Transition
        icon: mdi:transition-masked
        unit_of_measurement: 'Seconds'
        state: >
          {{ ((states.input_number.daytime_lighting_transition.state |
              int) * 60) }}
      - default_entity_id: sensor.next_sunrise
        name: Next Sunrise
        icon: mdi:weather-sunset-up
        state: >
          {{ (as_timestamp(states.sun.sun.attributes.next_dawn) |
              int | timestamp_custom("%H:%M", True)) }}
################################################################################
automation:
  ################################################################################
  - id: routine_day_outdoor_lights
    alias: 'Routine - Day - Outdoor Lights'
    trigger:
      - platform: sun
        event: sunrise
    condition:
      - condition: state
        entity_id: light.outdoor_lights
        state: 'on'
    action:
      - service: light.turn_off
        data:
          entity_id: light.outdoor_lights
  ################################################################################
  - id: routine_day_morning_lights
    alias: 'Routine - Day - Morning Lights'
    trigger:
      - platform: sun
        event: sunrise
    condition:
      - condition: state
        entity_id: light.morning_lights
        state: 'on'
    action:
      - service: light.turn_off
        data:
          entity_id: light.morning_lights
      - service: switch.turn_off
        data:
          entity_id: switch.ians_bed_safety_lights
  ################################################################################
  - id: routine_day_night_lights
    alias: 'Routine - Day - Night Lights'
    trigger:
      - platform: sun
        event: sunrise
    condition:
      - condition: state
        entity_id: light.night_lights
        state: 'on'
    action:
      - service: light.turn_off
        data:
          entity_id: light.night_lights
  ################################################################################

  # I realize this automation will be a little redundant, but it's just in case I
  # forget to turn shit off, or another automation fails.
  ################################################################################
  - id: routine_day_lighting_off
    alias: 'Routine - Day - Turn Off Lights After Sunrise'
    trigger:
      - platform: sun
        event: sunrise
        offset: '01:00:00'
    action:
      - service: light.turn_off
        data:
          entity_id:
            - light.indoor_lights
            - light.outdoor_lights
            - light.back_yard_string_lights
      - service: switch.turn_off
        data:
          entity_id: switch.ians_bed_safety_lights
################################################################################

################################################################################
# Scenes
################################################################################
scene:
  - name: Routine - Day - Morning Lights
    id: routine_day_morning_lights
    entities:
      # Living Areas
      light.living_room_ceiling_fan:
        state: 'on'

      # Hallways (moderate lighting for safety)
      light.downstairs_hallway_lights:
        state: 'on'
        brightness_pct: 50
      light.upstairs_hallway_lights:
        state: 'on'
        brightness_pct: 50

  - name: Routine - Day - Full Daylight
    id: routine_day_full_daylight
    entities:
      # Turn off all indoor lights to save energy during full daylight
      light.indoor_lights:
        state: 'off'
      light.outdoor_lights:
        state: 'off'
      light.back_yard_string_lights:
        state: 'off'
      light.foyer_chandelier:
        state: 'off'
################################################################################
