---
### Doge ###

# Feed the doge (@ & 15 minutes before 0800, 1200, & 1600)
# Add inputs for this later.
# 3 input datetime's & 1 input number
# This could be done as a single automation with a template
### Inputs ###
input_datetime:
  doge_meal_breakfast:
    name: Doge - Breakfast
    has_date: false
    has_time: true
  doge_meal_lunch:
    name: Doge - Lunch
    has_date: false
    has_time: true
  doge_meal_dinner:
    name: Doge - Dinner
    has_date: false
    has_time: true

input_number:
  doge_meal_advance:
    name: Doge - Meal - Advance
    icon: mdi:clock-in
    min: 0
    max: 60
    step: 5
    unit_of_measurement: Minutes
  doge_meal_duration:
    name: Doge - Meal - Duration
    icon: mdi:clock-outline
    min: 0
    max: 60
    step: 5
    unit_of_measurement: Minutes
  doge_meal_relief:
    name: Doge - Meal - Relief
    icon: mdi:clock-out
    min: 0
    max: 6
    step: 1
    unit_of_measurement: Hours

### Sensors ###
template:
  - sensor:
      # Breakfast
      - default_entity_id: sensor.doge_meal_breakfast
        name: Doge - Meal - Breakfast
        state: >
          {{ (states.input_datetime.doge_meal_breakfast.attributes.timestamp |
              int | timestamp_custom("%H:%M",False)) }}
      - default_entity_id: sensor.doge_meal_breakfast_advance
        name: Doge - Meal - Breakfast (Advance)
        state: >
          {{ ((states.input_datetime.doge_meal_breakfast.attributes.timestamp |
              int - states.input_number.doge_meal_advance.state |
              int * 60) | timestamp_custom("%H:%M",False)) }}
      - default_entity_id: sensor.doge_meal_breakfast_end
        name: Doge - Meal - Breakfast (End)
        state: >
          {{ ((states.input_datetime.doge_meal_breakfast.attributes.timestamp |
              int + states.input_number.doge_meal_duration.state |
              int * 60) | timestamp_custom("%H:%M",False)) }}
      - default_entity_id: sensor.doge_meal_breakfast_relief
        name: Doge - Meal - Breakfast (Relief)
        state: >
          {{ ((states.input_datetime.doge_meal_breakfast.attributes.timestamp |
              int + states.input_number.doge_meal_duration.state | int * 60 +
              states.input_number.doge_meal_relief.state | int * 60 * 60) |
              timestamp_custom("%H:%M",False)) }}
      # Lunch
      - default_entity_id: sensor.doge_meal_lunch
        name: Doge - Meal - Lunch
        state: >
          {{ (states.input_datetime.doge_meal_lunch.attributes.timestamp |
              int | timestamp_custom("%H:%M",False)) }}
      - default_entity_id: sensor.doge_meal_lunch_advance
        name: Doge - Meal - Lunch (Advance)
        state: >
          {{ ((states.input_datetime.doge_meal_lunch.attributes.timestamp |
              int - states.input_number.doge_meal_advance.state |
              int * 60) | timestamp_custom("%H:%M",False)) }}
      - default_entity_id: sensor.doge_meal_lunch_end
        name: Doge - Meal - Lunch (End)
        state: >
          {{ ((states.input_datetime.doge_meal_lunch.attributes.timestamp |
              int + states.input_number.doge_meal_duration.state |
              int * 60) | timestamp_custom("%H:%M",False)) }}
      - default_entity_id: sensor.doge_meal_lunch_relief
        name: Doge - Meal - Lunch (Relief)
        state: >
          {{ ((states.input_datetime.doge_meal_lunch.attributes.timestamp |
              int + states.input_number.doge_meal_duration.state | int * 60 +
              states.input_number.doge_meal_relief.state | int * 60 * 60) |
              timestamp_custom("%H:%M",False)) }}
      # Dinner
      - default_entity_id: sensor.doge_meal_dinner
        name: Doge - Meal - Dinner
        state: >
          {{ (states.input_datetime.doge_meal_dinner.attributes.timestamp |
              int | timestamp_custom("%H:%M",False)) }}
      - default_entity_id: sensor.doge_meal_dinner_advance
        name: Doge - Meal - Dinner (Advance)
        state: >
          {{ ((states.input_datetime.doge_meal_dinner.attributes.timestamp |
              int - states.input_number.doge_meal_advance.state |
              int * 60) | timestamp_custom("%H:%M",False)) }}
      - default_entity_id: sensor.doge_meal_dinner_end
        name: Doge - Meal - Dinner (End)
        state: >
          {{ ((states.input_datetime.doge_meal_dinner.attributes.timestamp |
              int + states.input_number.doge_meal_duration.state |
              int * 60) | timestamp_custom("%H:%M",False)) }}
      - default_entity_id: sensor.doge_meal_dinner_relief
        name: Doge - Meal - Dinner (Relief)
        state: >
          {{ ((states.input_datetime.doge_meal_dinner.attributes.timestamp |
              int + states.input_number.doge_meal_duration.state | int * 60 +
              states.input_number.doge_meal_relief.state | int * 60 * 60) |
              timestamp_custom("%H:%M",False)) }}
      # Location
      - default_entity_id: sensor.distance_from_doge
        name: Distance From Doge
        state: >
          {{ distance('device_tracker.michio_tracker','person.ian') }}
        unit_of_measurement: km
automation:
  ################################################################################
  - id: routine_doge_breakfast
    alias: Routine - Doge - Breakfast
    trigger:
      - platform: template
        value_template: >
          {{ (states.sensor.time.state
            == states.sensor.doge_meal_breakfast.state) }}
    condition:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'
    action:
      - service: notify.notify
        data:
          title: It's Breakfast Time!
          message: Get up and go feed the doge!
  ################################################################################
  - id: routine_doge_breakfast_upcoming
    alias: Routine - Doge - Breakfast (Upcoming)
    trigger:
      - platform: template
        value_template: >
          {{ (states.sensor.time.state
            == states.sensor.doge_meal_breakfast_advance.state) }}
    condition:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'
    action:
      - service: notify.notify
        data:
          title: It's Almost Breakfast Time!
          message: Get ready to get up and go feed the doge!
  ################################################################################
  - id: routine_doge_breakfast_relief
    alias: Routine - Doge - Breakfast (Relief)
    trigger:
      - platform: template
        value_template: >
          {{ (states.sensor.time.state
            == states.sensor.doge_meal_breakfast_relief.state) }}
    condition:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'
    action:
      - service: notify.notify
        data:
          title: Take The Doge Out!
          message: Time to empty the doge!
  ################################################################################
  - id: routine_doge_lunch
    alias: Routine - Doge - Lunch
    trigger:
      - platform: template
        value_template: >
          {{ (states.sensor.time.state
            == states.sensor.doge_meal_lunch.state) }}
    condition:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'
    action:
      - service: notify.notify
        data:
          title: It's Lunch Time!
          message: Get up and go feed the doge!
  ################################################################################
  - id: routine_doge_lunch_upcoming
    alias: Routine - Doge - Lunch (Upcoming)
    trigger:
      - platform: template
        value_template: >
          {{ (states.sensor.time.state
            == states.sensor.doge_meal_lunch_advance.state) }}
    condition:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'
    action:
      - service: notify.notify
        data:
          title: It's Almost Lunch Time!
          message: Get ready to get up and go feed the doge!
  ################################################################################
  - id: routine_doge_lunch_relief
    alias: Routine - Doge - Lunch (Relief)
    trigger:
      - platform: template
        value_template: >
          {{ (states.sensor.time.state
            == states.sensor.doge_meal_lunch_relief.state) }}
    condition:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'
    action:
      - service: notify.notify
        data:
          title: Take The Doge Out!
          message: Time to empty the doge!
  ################################################################################
  - id: routine_doge_dinner
    alias: Routine - Doge - Dinner
    trigger:
      - platform: template
        value_template: >
          {{ (states.sensor.time.state
            == states.sensor.doge_meal_dinner.state) }}
    condition:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'
    action:
      - service: notify.notify
        data:
          title: It's Dinner Time!
          message: Get up and go feed the doge!
  ################################################################################
  - id: routine_doge_dinner_upcoming
    alias: Routine - Doge - Dinner (Upcoming)
    trigger:
      - platform: template
        value_template: >
          {{ (states.sensor.time.state
            == states.sensor.doge_meal_dinner_advance.state) }}
    condition:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'
    action:
      - service: notify.notify
        data:
          title: It's Almost Dinner Time!
          message: Get ready to get up and go feed the doge!
  ################################################################################
  - id: routine_doge_dinner_relief
    alias: Routine - Doge - Dinner (Relief)
    trigger:
      - platform: template
        value_template: >
          {{ (states.sensor.time.state
            == states.sensor.doge_meal_dinner_relief.state) }}
    condition:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'
    action:
      - service: notify.notify
        data:
          title: Take The Doge Out!
          message: Time to empty the doge!
  ################################################################################
  - id: routine_doge_collar_light
    alias: Routine - Doge - Collar Light
    trigger:
      - platform: sun
        event: sunset
      - platform: sun
        event: sunrise
      - platform: state
        entity_id:
          - input_boolean.away_mode
          - light.michio_collar_light
    action:
      - alias: 'State Handler'
        choose:
          - conditions:
              - alias: 'Home'
                condition: state
                entity_id: input_boolean.away_mode
                state: 'off'
            sequence:
              - alias: 'Turn off Light'
                service: light.turn_off
                target:
                  entity_id: light.michio_collar_light
          - conditions:
              - alias: 'Away'
                condition: state
                entity_id: input_boolean.away_mode
                state: 'on'
            sequence:
              - alias: 'Time'
                choose:
                  - conditions:
                      - alias: 'Day'
                        condition: state
                        entity_id: sun.sun
                        state: 'above_horizon'
                    sequence:
                      - alias: 'Turn off Light'
                        service: light.turn_off
                        target:
                          entity_id: light.michio_collar_light
                  - conditions:
                      - alias: 'Night'
                        condition: state
                        entity_id: sun.sun
                        state: 'below_horizon'
                    sequence:
                      - alias: 'Turn on Light'
                        service: light.turn_on
                        target:
                          entity_id: light.michio_collar_light
################################################################################
