---
################################################################################
# Event Routines
################################################################################

# This configuration is mainly for automating things around the house for
# specific events and days. A couple of ideas that I'm working with are:
# - Party lights for game nights (monthly)
# - Green lights for St. Patrick's Day

automation:
  ################################################################################
  - id: routine_events_game_night
    alias: 'Routine - Events - Game Night'
    trigger:
      - platform: time
        at: '18:00:00'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: group.people
          state: home
        - condition: template
          # on the 4th saturday of the month
          value_template: >
            "{{ ( now().isocalendar()[2] == 6 
                  and now().day >= 22 
                  and now().day <= 28 ) }}"
    action:
      # I've copied all of the sounds from the iOS app to use across the house
      # https://github.com/home-assistant/iOS/tree/master/HomeAssistant/Sounds
      # US-EN-Morgan-Freeman-Starting-Party-Mode.wav
      # However, it seems like the notify.alexa_media component won't do mp3s
      # Keeping this note here for later.
      - service: script.notification_party_mode
      - service: input_boolean.turn_on
        entity_id: input_boolean.party_lights
      - delay:
          # Turn it off at midnight. 6 hours. 360 minutes.
          minutes: 360
      - service: input_boolean.turn_off
        entity_id: input_boolean.party_lights
################################################################################

script:
  ################################################################################
  notification_party_mode:
    alias: 'Notification - Party Mode'
    sequence:
      - service: media_player.volume_set
        entity_id:
          - media_player.downstairs_thermostat
          - media_player.upstairs_thermostat
          - media_player.ian_s_echo_dot
        data:
          volume_level: '1.0'
      - service: notify.alexa_media
        data:
          data:
            type: tts
          target:
            - media_player.downstairs_thermostat
            - media_player.upstairs_thermostat
            - media_player.ian_s_echo_dot
          message: 'Party mode activated.'
################################################################################
