---
### Nighttime Routines ###

################################################################################
# Inputs
################################################################################
input_datetime:
  bedtime:
    name: Bedtime
    has_date: false
    has_time: true
    # initial: '21:00'
  last_call:
    name: Last Call
    has_date: false
    has_time: true

input_number:
  nighttime_delay:
    name: Night Time Delay
    icon: mdi:clock-in
    # initial: 60
    min: 0
    max: 60
    step: 5
    unit_of_measurement: Minutes

  nighttime_lighting_transition:
    name: Night Time Lighting Transition
    icon: mdi:clock-in
    # initial: 15
    min: 0
    max: 30
    step: 5
    unit_of_measurement: Minutes
################################################################################

sensor:
  ################################################################################
  - platform: template
    sensors:
      bedtime:
        friendly_name: Bedtime
        icon_template: mdi:clock-outline
        value_template: >
          {{ (states.input_datetime.bedtime.attributes.timestamp | int |
              timestamp_custom("%H:%M",False)) }}
      nighttime_start:
        friendly_name: Night Time Start
        icon_template: mdi:clock-outline
        value_template: >
          {{ (((states.input_datetime.bedtime.attributes.timestamp | int) +
              (states.input_number.nighttime_delay.state | int * 60)) |
              timestamp_custom("%H:%M",False)) }}
      nighttime_lighting_transition:
        friendly_name: Night Time Lighting
        icon_template: mdi:transition-masked
        unit_of_measurement: 'Seconds'
        value_template: >
          {{ ((states.input_number.nighttime_lighting_transition.state |
              int) * 60) }}
      last_call:
        friendly_name: Last Call
        icon_template: mdi:clock-outline
        value_template: >
          {{ (states.input_datetime.last_call.attributes.timestamp | int |
              timestamp_custom("%H:%M",False)) }}
      next_sunset:
        friendly_name: Next Sunset
        icon_template: mdi:weather-sunset-down
        value_template: >
          {{ (as_timestamp(states.sun.sun.attributes.next_dusk) | int |
              timestamp_custom("%H:%M", True)) }}
################################################################################
automation:
  ################################################################################
  - id: routine_night_outdoor_lights
    alias: 'Routine - Night - Outdoor Lights'
    trigger:
      - platform: sun
        event: sunset
    action:
      - alias: 'Turn on the lights'
        service: light.turn_on
        data:
          entity_id: light.outdoor_lights
          profile: relax
          brightness_pct: 50
  ################################################################################
  - id: routine_night_night_lights
    alias: 'Routine - Night - Night Lights'
    trigger:
      - platform: sun
        event: sunset
    action:
      - alias: 'Turn on the lights'
        service: light.turn_on
        data:
          entity_id: light.night_lights
          profile: relax
          brightness_pct: 50
  ################################################################################
  - id: routine_night_master_bedroom_lights
    alias: 'Routine - Night - Master Bedroom Lights'
    trigger:
      - platform: sun
        event: sunset
    condition:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'
    action:
      - alias: 'Turn on the lights'
        service: light.turn_on
        data:
          entity_id: light.master_bedroom_lights
          brightness_pct: 100
          profile: relax
  ################################################################################
  - id: routine_night_evening_lights
    alias: 'Routine - Night - Evening Lights'
    trigger:
      - platform: sun
        event: sunset
    condition:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'
    action:
      - alias: 'Turn on the lights'
        service: light.turn_on
        data:
          entity_id:
            - light.upstairs_hallway_lights
            - light.downstairs_hallway_lights
          brightness_pct: 25
          profile: relax
  ################################################################################
  - id: routine_night_bedtime
    alias: 'Routine - Night - Bedtime'
    trigger:
      - platform: template
        value_template: >
          {{ states.sensor.time.state == states.sensor.nighttime_start.state }}
    condition:
      condition: state
      entity_id: binary_sensor.worknight
      state: 'on'
    action:
      - alias: 'Turn off the lights'
        service: light.turn_off
        data:
          entity_id:
            # - light.living_room_ceiling_fan
            - light.dining_room_chandelier
  ################################################################################
  - id: routine_night_last_call
    alias: 'Routine - Night - Last Call'
    trigger:
      - platform: template
        value_template: >
          {{ states.sensor.time.state == states.sensor.last_call.state }}
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.worknight
            state: 'on'
          - condition: state
            entity_id: light.master_bedroom_lights
            state: 'on'
    action:
      # - service: notify.alexa_media
      #   data:
      #     data:
      #       type: tts
      #     target:
      #       - media_player.downstairs_thermostat
      #       - media_player.upstairs_thermostat
      #     message: 'Go the phuque to sleep!'
      #     # TODO https://www.youtube.com/watch?v=Udj-o2m39NA
      # Turn out the lights
      - alias: 'Turn off the lights'
        service: light.turn_off
        data:
          entity_id:
            - light.master_bedroom_lights
            - light.lights_out
################################################################################

################################################################################
# Scenes
################################################################################
scene:
  - name: Routine - Night - Evening Lights
    id: routine_night_evening_lights
    entities:
      # Outdoor Lights (50% brightness, relax profile)
      light.front_porch_light_left:
        state: 'on'
        brightness_pct: 50
        profile: relax
      light.front_porch_light_right:
        state: 'on'
        brightness_pct: 50
        profile: relax
      light.outdoor_garage_light_right:
        state: 'on'
        brightness_pct: 50
        profile: relax
      light.outdoor_garage_light_left:
        state: 'on'
        brightness_pct: 50
        profile: relax
      light.outdoor_garage_light_side:
        state: 'on'
        brightness_pct: 50
        profile: relax
      light.back_door_light:
        state: 'on'
        brightness_pct: 50
        profile: relax

      # Night Lights (50% brightness)
      light.sitting_room_floor_lamp:
        state: 'on'
        brightness_pct: 50
      light.kitchen_cabinet_lights:
        state: 'on'
        brightness_pct: 50
      light.kitchen_sink_light:
        state: 'on'
        brightness_pct: 50
      light.living_room_tv_lights:
        state: 'on'
        brightness_pct: 50

      # Master Bedroom Lights (100% brightness)
      light.master_bedroom_floor_lamp:
        state: 'on'
        brightness_pct: 100
        profile: relax
      light.master_bedroom_table_lamps:
        state: 'on'
        brightness_pct: 100

      # Evening Lights (25% brightness)
      light.back_yard_string_lights:
        state: 'on'
        brightness_pct: 50
      light.downstairs_hallway_lights:
        state: 'on'
        brightness_pct: 25
      light.upstairs_hallway_lights:
        state: 'on'
        brightness_pct: 25
      light.office_floor_lamp:
        state: 'on'
        brightness_pct: 50
        profile: relax
      light.living_room_ceiling_fan:
        state: 'on'
      light.studio_floor_lamp:
        state: 'on'
        brightness_pct: 50
        profile: relax
      light.music_room_floor_lamp:
        state: 'on'
        brightness_pct: 50
        profile: relax

      # Hyperion Lights
      light.hyperion_living_room_tv:
        state: 'on'
      light.hyperion_kitchen_cabinet_lights:
        state: 'on'
  ################################################################################
  - name: Routine - Night - Goodnight
    id: routine_night_goodnight
    entities:
      # Living Room
      light.living_room_lights:
        state: 'off'
      light.living_room_tv_lights:
        state: 'off'

      # Kitchen
      light.kitchen_lights:
        state: 'off'
      light.kitchen_cabinet_lights:
        state: 'off'
      light.kitchen_chandelier:
        state: 'off'

      # Dining Room
      light.dining_room_chandelier:
        state: 'off'

      # Office
      light.office_lights:
        state: 'off'
      light.office_floor_lamp:
        state: 'off'

      # Downstairs and Upstairs
      light.downstairs_hallway_lights:
        state: 'off'
      light.garage_hallway_light:
        state: 'off'
      light.upstairs_hallway_lights:
        state: 'off'

      # Studio and Music Room
      light.studio_floor_lamp:
        state: 'off'
      light.music_room_floor_lamp:
        state: 'off'

      # Master Bedroom
      light.master_bedroom_floor_lamp:
        state: 'off'
      light.master_bedroom_table_lamps:
        state: 'off'
      light.master_bathroom_closet_light:
        state: 'off'
      light.master_bathroom_vanity_lights:
        state: 'off'
      light.master_bathroom_shower_lights:
        state: 'off'
      light.master_bathroom_toilet_light:
        state: 'off'

      # Back Yard
      light.back_yard_string_lights:
        state: 'off'
################################################################################
