### Daytime Routines ###

automation:
################################################################################
  - id: routine_day_front_porch_lights
    alias: 'Routine - Front Porch Lights'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sun.sun
        from: 'below_horizon'
        to: 'above_horizon'
    action:
      - service: light.turn_off
        data:
          entity_id: light.front_porch_lights
          transition: 900
################################################################################

################################################################################
  - id: routine_day_living_room_lights
    alias: 'Routine - Day - Living Room Lights'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sun.sun
        from: 'below_horizon'
        to: 'above_horizon'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: sun.sun
        state: 'above_horizon'
      - condition: state
        entity_id: light.living_room_floor_lamp
        state: 'on'
    action:
      - service: light.turn_off
        data:
          entity_id: light.living_room_floor_lamp
          transition: 900
################################################################################
