---
### Work ###

# Inputs
input_datetime:
  routine_work_start:
    name: Routine - Work - Start
    has_date: false
    has_time: true
  routine_work_stop:
    name: Routine - Work - Stop
    has_date: false
    has_time: true

# Sensors
binary_sensor:
  - platform: template
    sensors:
      routine_work_active:
        friendly_name: Routine - Work - Active
        value_template: >
          {{ today_at(states('input_datetime.routine_work_start')) <
          now() < today_at(states('input_datetime.routine_work_stop')) }}
      routine_work_test:
        friendly_name: Routine - Work - Test
        value_template: >
          {{ is_state('schedule.routine_work_schedule', 'on') and
          is_state('binary_sensor.workday', 'on') }}
  # Workday
  - platform: workday
    name: workday
    country: US

  # Worknight
  - platform: workday
    name: worknight
    country: US
    days_offset: 1

# Work Schedule
schedule:
  routine_work_schedule:
    name: Routine - Work - Schedule
    monday:
      - from: '09:00:00'
        to: '15:00:00'
    tuesday:
      - from: '09:00:00'
        to: '15:00:00'
    wednesday:
      - from: '09:00:00'
        to: '15:00:00'
    thursday:
      - from: '09:00:00'
        to: '15:00:00'

# Automations
automation:
  ###############################################################################
  - id: routine_work_meetings
    alias: Routine - Work - Meetings
    trigger:
      - platform: state
        entity_id: calendar.work
    condition:
      - alias: 'Ian is home'
        condition: state
        entity_id: person.ian
        state: 'home'
    action:
      - alias: 'Status handler'
        choose:
          - conditions:
              - alias: 'Meeting Started'
                condition: state
                entity_id: calendar.work
                state: 'on'
            sequence:
              - alias: 'Turn on key light'
                service: light.turn_on
                target:
                  entity_id: light.office_key_light
              - alias: 'Set doorbell message'
                service: select.select_option
                data:
                  entity_id: select.front_door_doorbell_text
                  option: In Meeting
          - conditions:
              - alias: 'Meeting Ended'
                condition: state
                entity_id: calendar.work
                state: 'off'
            sequence:
              - alias: 'Turn on key light'
                service: light.turn_off
                target:
                  entity_id: light.office_key_light
              - alias: 'Set doorbell message'
                service: select.select_option
                data:
                  entity_id: select.front_door_doorbell_text
                  option: Go Away
  ###############################################################################
  - id: routine_work_start
    alias: Routine - Work - Start
    trigger:
      - platform: time
        at: input_datetime.routine_work_start
    condition:
      - alias: 'Only on workdays'
        condition: state
        entity_id: binary_sensor.workday
        state: 'on'
      - alias: 'Only during work hours'
        condition: state
        entity_id: binary_sensor.routine_work_active
        state: 'on'
    action:
      - alias: 'Turn on office lights'
        service: light.turn_on
        target:
          entity_id:
            - light.office_floor_lamp
            - light.office_panel_lights_south
            - light.office_panel_lights_west
            # - light.office_workbench
      - alias: 'Set brightness for office floor lamp'
        service: light.turn_on
        target:
          entity_id: light.office_floor_lamp
        data:
          brightness: 100%
      - alias: 'Stop the vacuums'
        service: vacuum.stop
        target:
          entity_id:
            - vacuum.downstairs
            - vacuum.upstairs
      - delay: 00:00:01
      - alias: 'Return vacuums to docks'
        service: vacuum.return_to_base
        target:
          entity_id:
            - vacuum.downstairs
            - vacuum.upstairs
  ###############################################################################
  - id: routine_work_break
    alias: Routine - Work - Break
    trigger:
      - platform: state
        entity_id: input_boolean.away_mode
    condition:
      - alias: 'Only on workdays'
        condition: state
        entity_id: binary_sensor.workday
        state: 'on'
      - alias: 'During Work Hours'
        condition: state
        entity_id: binary_sensor.routine_work_active
        state: 'on'
    action:
      - alias: 'State Handler'
        choose:
          - conditions:
              - alias: 'Left the house'
                condition: state
                entity_id: input_boolean.away_mode
                state: 'on'
            sequence:
              - alias: 'Turn off office lights'
                service: light.turn_off
                target:
                  entity_id:
                    - light.office_panel_lights_south
                    - light.office_panel_lights_west
          - conditions:
              - alias: 'Returned'
                condition: state
                entity_id: input_boolean.away_mode
                state: 'off'
            sequence:
              - alias: 'Turn on office lights'
                service: light.turn_on
                target:
                  entity_id:
                    - light.office_panel_lights_south
                    - light.office_panel_lights_west
  ###############################################################################
  - id: routine_work_stop
    alias: Routine - Work - Stop
    trigger:
      - platform: time
        at: input_datetime.routine_work_stop
    condition:
      - alias: 'Only on workdays'
        condition: state
        entity_id: binary_sensor.workday
        state: 'on'
      - alias: 'During Work Hours'
        condition: state
        entity_id: binary_sensor.routine_work_active
        state: 'on'
    action:
      - alias: 'Turn off office lights'
        service: light.turn_off
        target:
          entity_id:
            - light.office_floor_lamp
            - light.office_panel_lights_south
            - light.office_panel_lights_west
            # - light.office_workbench
###############################################################################
