### Blinds ###

# This package will define the template behavior for the blinds motors
# across the house. The goal is to minimize the sun's glare in the afternoon,
# and improve energy efficiency by not opening the blinds when it's too cold.

# There are 4 primary automations that this package
# will define:
# - Morning (Open)
# - Afternoon (Close)
# - Sunset (Open)
# - Bedtime (Close)

# Additionally, I will group all of the blinds to ensure testing will continue
# as more blinds motors are installed, eventually branching to automation sets
# for each area with blinds on the western-facing side of the house.

cover:
  - name: Blinds
    platform: group
    entities:
      - cover.office_blinds

# Create an input boolean to centralize some checks for opening the blinds.
input_boolean:
  blinds_lock:
    name: Blinds Lock

# And dynamically set the icon
homeassistant:
  customize:
    input_boolean.blinds_lock:
      templates:
          icon: >
            if (state === 'on') return 'mdi:lock';
            return 'mdi:lock-open';

automation:
################################################################################
  - id: project_blinds_lock
    alias: Project - Blinds - Lock
    trigger:
      - platform: state
        entity_id: input_boolean.away_mode
      - platform: numeric_state
        entity_id: weather.dark_sky
        attribute: temperature
        above: 32 # 0 C
        below: 32 # 0 C
    action:
      - alias: "State Handler"
        choose:
        - conditions:
          - condition: and
            conditions:
            - alias: "Above Freezing"
              condition: numeric_state
              entity_id: weather.dark_sky # Replace Dark Sky...
              attribute: temperature
              above: 32 # 0 C
            - alias: "Someone is home"
              condition: state
              entity_id: input_boolean.away_mode
              state: "off"
            - alias: "Alarm is disarmed"
              condition: state
              entity_id: alarm_control_panel.home
              state: "disarmed"
          sequence:
            - alias: "Disable Lock"
              service: input_boolean.turn_off
              target:
                entity_id: input_boolean.blinds_lock
        - conditions:
          - condition: or
            conditions:
            - alias: "Below Freezing"
              condition: numeric_state
              entity_id: weather.dark_sky # Replace Dark Sky...
              attribute: temperature
              below: 32 # 0 C
            - alias: "Nobody is home"
              condition: state
              entity_id: input_boolean.away_mode
              state: "on"
            - alias: "Alarm is armed"
              condition: state
              entity_id: alarm_control_panel.home
              state: "armed"
          sequence:
            - alias: "Enable Lock"
              service: input_boolean.turn_on
              target:
                entity_id: input_boolean.blinds_lock
################################################################################
  - id: project_blinds_morning
    alias: Project - Blinds - Morning
    trigger:
      - platform: sun
        event: sunrise
    condition:
      - alias: "Blinds Unlocked"
        condition: state
        entity_id: input_boolean.blinds_lock
        state: "off"
    action:
      - alias: "Morning - Open"
        service: cover.blinds
        target:
          entity_id: cover.office_blinds
################################################################################
  - id: project_blinds_afternoon
    alias: Project - Blinds - Afternoon
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        attrubute: azimuth
        above: 150 # The intersection of my home's western face.
    action:
      - alias: "Afternoon - Close"
        service: cover.close_cover
        target:
          entity_id: cover.blinds
################################################################################
  - id: project_blinds_sunset
    alias: Project - Blinds - Sunset
    trigger:
      - platform: sun
        event: sunset
        # 5 Minutes before. Enjoy the sunset.
        offset: "-00:05:00"
    condition:
      - alias: "Blinds Unlocked"
        condition: state
        entity_id: input_boolean.blinds_lock
        state: "off"  
    action:
      - alias: "Sunset - Open"
        service: cover.open_cover
        target:
          entity_id: cover.blinds
################################################################################
  - id: project_blinds_night
    alias: Project - Blinds - Night
    trigger:
      # Close blinds at night
      - platform: time
        at: "23:00:00"
    action:
      - alias: "Night - Close"
        service: cover.close_cover
        target:
          entity_id: cover.blinds
################################################################################
  - id: project_blinds_close
    alias: Project - Blinds - Away
    trigger:
      # Close blinds when alarm is armed
      - platform: state
        entity_id: alarm_control_panel.home
        from: "disarmed"
        to: "armed"
      # Close blinds when the house is empty
      - platform: state
        entity_id: input_boolean.away_mode
        from: "off"
        to: "on"
    action:
      - alias: "Blinds Close"
        service: cover.close_cover
        target:
          entity_id: cover.blinds
################################################################################