### Plex ###

# From media_players.yaml
media_player:
# Plex Media Server
  - platform: plex
    entity_namespace: plex
    show_all_controls: true

# From sensors.yaml
sensor:
# Plex Activity Monitor
  - platform: plex
    host: !secret plex_host
    port: !secret plex_port
    name: Plex
    username: !secret plex_username
    password: !secret plex_password
    server: !secret plex_server
    token: !secret plex_token