---
### Jokes ###
automation:
  ###############################################################################
  # Using the distance sensor in presence.yaml
  - id: toys_jokes_distance_trouble
    alias: 'Toys - Jokes - Distance Trouble'
    trigger:
      - platform: numeric_state
        entity_id: sensor.distance_apart
        above: 100
        for: '01:00:00'
    action:
      - service: notify.mobile_app_aimees_iphone
        data:
          title: "You're kinda far away"
          message: |
            "Is it really a good idea to leave Ian unattended for this long?"

###############################################################################
