---
ssid: !secret esphome_wifi_ssid
password: !secret esphome_wifi_password
domain: !secret esphome_domain
fast_connect: !secret esphome_fast_connect
# Enable fallback hotspot (captive portal) in case wifi connection fails
ap:
  password: !secret esphome_wifi_password
