### Morning Routines ###

group:
################################################################################
  morning_settings:
    name: Morning Settings
    control: hidden
    entities:
      - input_datetime.morning
      - input_number.morning_advance
      - sensor.morning_start
################################################################################

################################################################################
# Inputs
################################################################################
input_datetime:
  morning:
    name: Morning
    has_date: false
    has_time: true
    initial: '05:00'

input_number:
  morning_advance:
    name: Morning Advance
    icon: mdi:clock-in
    initial: 60
    min: 0
    max: 120
    step: 15
################################################################################

sensor:
################################################################################
  - platform: template
    sensors:
      morning:
        friendly_name: Morning
        entity_id: input_datetime.morning
        value_template: >
          {{ states.input_datetime.morning.attributes.timestamp | int | timestamp_custom("%H:%M",False) }}
      morning_start:
        friendly_name: Morning Start
        entity_id: input_datetime.morning, input_number.morning_advance
        value_template: >
          {{ ((states.input_datetime.morning.attributes.timestamp | int) - (states.input_number.morning_advance.state | int * 60)) | timestamp_custom("%H:%M",False) }}
################################################################################

automation:
################################################################################
  - id: master_bedroom_lights_morning
    alias: "Routine - Morning - Master Bedroom Lights"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: 
        - device_tracker.network_ians_iphone
        - device_tracker.network_aimees_iphone
        to: 'not_home'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: device_tracker.network_ians_iphone
        state: 'not_home'
      - condition: state
        entity_id: device_tracker.network_aimees_iphone
        state: 'not_home'
    action:
      - service: light.turn_off
        data:
          entity_id: light.master_bedroom_lights
################################################################################

################################################################################
  - id: routine_morning_alarm_disarm
    alias: 'Routine - Morning - Alarm Disarm'
    initial_state: 'on'
    trigger:
    - platform: template
      value_template: >
        {{ states.sensor.time.state == states.sensor.wakeup_alarm_start_time.state }}
    condition:
      condition: state
      entity_id: binary_sensor.workday
      state: 'on'
    action:
      service: alarm_control_panel.alarm_disarm
      data:
        entity_id: alarm_control_panel.home
        code: !secret alarm_code
################################################################################