---
# Bed Occupancy Sensor
###############################################################################
# The following configuration is for a bed occupancy sensor powered by two
# individual HX711 load cell amplifiers used to detect weight on either side
# of my bed. This will be used for assisting with automations to tell if we're
# out of bed yet and potentially monitoring the quality of sleep we're getting.
###############################################################################

esphome:
  name: bed_occupancy_sensor
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret esphome_wifi_ssid
  password: !secret esphome_wifi_password
  domain: !secret esphome_domain
  fast_connect: !secret esphome_fast_connect
  power_save_mode: none

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret esphome_bed_occupancy_sensor_ssid
    password: !secret esphome_bed_occupancy_sensor_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_api

ota:
  password: !secret esphome_ota
  
sensor:
  - platform: hx711
    name: "Bed Weight (Ian)"
    id: bed_weight_ian
    dout_pin: D4
    clk_pin: D3
    filters:
      - calibrate_linear:
          - 1600 -> 0
          - 145000 -> 5.6
      - sliding_window_moving_average:
          window_size: 5
          send_every: 5
    update_interval: 60s
    unit_of_measurement: lb
    accuracy_decimals: 2

  - platform: hx711
    name: "Bed Weight (Aimee)"
    id: bed_weight_aimee
    dout_pin: D6
    clk_pin: D5
    filters:
      - calibrate_linear:
          - 2000 -> 0
          - 145000 -> 5.6
      - sliding_window_moving_average:
          window_size: 5
          send_every: 5
    update_interval: 60s
    unit_of_measurement: lb
    accuracy_decimals: 2

binary_sensor:
  - platform: template
    name: "Bed Occupancy (Ian)"
    device_class: occupancy
    lambda: |-
      if (id(bed_weight_ian).state > 10) {
        return true;
      } else {
        return false;
      }

  - platform: template
    name: "Bed Occupancy (Aimee)"
    device_class: occupancy
    lambda: |-
      if (id(bed_weight_aimee).state > 10) {
        return true;
      } else {
        return false;
      }