# Garage Door Opener
###############################################################################
# The following configuration is for a custom garage door opener that I have
# built using simple reed switches and relays connected to a Wemos D1 Mini.
# Parts Used:
# - Wemos D1 Mini:  https://www.aliexpress.com/item/32651747570.html
# - Reed Switch:    https://www.aliexpress.com/item/33022073463.html
# - Relay Module:   https://www.aliexpress.com/item/32997387727.html
###############################################################################

esphome:
  name: garage_door_opener
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret esphome_wifi_ssid
  password: !secret esphome_wifi_password
  domain: !secret esphome_domain
  fast_connect: !secret esphome_fast_connect

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret esphome_garage_door_opener_ssid
    password: !secret esphome_garage_door_opener_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_api

ota:
  password: !secret esphome_ota

# Begin Configuration

# Pinout
# D1 = Door 01 Sensor
# D2 = Door 02 Sensor
# D3 = Door 01 Relay
# D4 = Door 02 Relay

# Switch
switch:
  - platform: gpio
    pin: D3
    name: "Garage Door 01 Switch"
    id: garage_door_01_switch
  - platform: gpio
    pin: D4
    name: "Garage Door 02 Switch"
    id: garage_door_02_switch

# Sensor
binary_sensor:
  - platform: gpio
    pin: D1
    name: "Garage Door 01 Sensor"
    device_class: garage_door
    id: garage_door_01_sensor
  - platform: gpio
    pin: D2
    name: "Garage Door 02 Sensor"
    device_class: garage_door
    id: garage_door_02_sensor

# Cover
cover:
  - platform: template
    name: "Garage Door 01"
    id: garage_door_01
    lambda: !lambda |-
      if (id(garage_door_01_sensor).state) {
        return COVER_CLOSED;
      } else {
        return COVER_OPEN;
      }
  - platform: template
    name: "Garage Door 02"
    id: garage_door_02
    lambda: !lambda |-
      if (id(garage_door_02_sensor).state) {
        return COVER_CLOSED;
      } else {
        return COVER_OPEN;
      }
    