---
<<: !include common/diagnostics.yaml

substitutions:
  name: home-assistant-voice-09c9b4
  friendly_name: Office Voice

packages:
  Nabu Casa.Home Assistant Voice PE: github://esphome/home-assistant-voice-pe/home-assistant-voice.yaml

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

wifi: !include common/wifi.yaml

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret home_assistant_api_encryption_key

ota:
  platform: esphome
  password: !secret esphome_ota

captive_portal:
