---
substitutions:
  name: 'living-room-tv-outlet'
  friendly_name: Living Room TV Outlet

packages:
  Athom_Technology.Smart_Plug_V2: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

# Enable Home Assistant API
api:
  encryption:
    key: !secret home_assistant_api_encryption_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
