---
substitutions:
  name: master-bed-remote
  friendly_name: Master Bedroom Remote
  room: Master Bedroom
  # renovate: datasource=github-releases depName=athom-tech/esp32-configs versioning=semver extractVersion=^esphome-(?<version>.*)$
  version: 2026.7.3

packages:
  Athom_Technology.RF_IR_Remote: github://athom-tech/esp32-configs/athom-rf-ir-remote.yaml@esphome-${version}

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  area: ${room}

esp32_ble:
  name: ${name}

# Don't let Athom's managed OTA overwrite this build with stock firmware
update:
  - id: !remove update_http_request

api:
  encryption:
    key: !secret home_assistant_api_encryption_key

wifi: !include common/wifi.yaml
