---
# Master Bedroom Bluetooth Proxy
<<: !include common/diagnostics.yaml

substitutions:
  name: master-bedroom-bluetooth-proxy
  friendly_name: Master Bedroom Bluetooth Proxy

esphome:
  name: master-bedroom-bluetooth-proxy
  friendly_name: Master Bedroom Bluetooth Proxy
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi: !include common/wifi.yaml

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret home_assistant_api_encryption_key

ota:
  platform: esphome
  password: !secret esphome_ota

esp32_ble_tracker:
  scan_parameters:
    # We currently use the defaults to ensure Bluetooth
    # can co-exist with WiFi In the future we may be able to
    # enable the built-in coexistence logic in ESP-IDF
    active: true

bluetooth_proxy:
  active: true

button:
  - platform: safe_mode
    id: button_safe_mode
    name: Safe Mode Boot

  - platform: factory_reset
    id: factory_reset_btn
    name: Factory reset
