---
# Mycology Air Quality Sensor
<<: !include common/diagnostics.yaml

esphome:
  name: mycology-air-quality-sensor
  friendly_name: Mycology Air Quality Sensor

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

wifi: !include common/wifi.yaml

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret home_assistant_api_encryption_key

ota:
  platform: esphome
  password: !secret esphome_ota

captive_portal:

# AirGradient Open Air Outdoor Monitor with CO2 and TVOC
# Model: O-1PST
# https://www.airgradient.com/open-airgradient/instructions/overview/

substitutions:
  name: mycology-air-quality-sensor
  friendly_name: Mycology Air Quality Sensor
  # renovate: datasource=github-releases depName=MallocArray/airgradient_esphome
  config_version: 5.3.0
  # Must have quotes around value
  name_add_mac_suffix: 'false'

dashboard_import:
  package_import_url: github://MallocArray/airgradient_esphome/airgradient-open-air-o-1pst.yaml
  import_full_config: false

packages:
  board: github://MallocArray/airgradient_esphome/packages/airgradient_esp32-c3_board.yaml
  captive_portal: github://MallocArray/airgradient_esphome/packages/captive_portal.yaml
  # pm_2.5: github://MallocArray/airgradient_esphome/packages/sensor_pms5003t.yaml
  pm_2.5: github://MallocArray/airgradient_esphome/packages/sensor_pms5003t_extended_life.yaml
  co2: github://MallocArray/airgradient_esphome/packages/sensor_s8.yaml
  tvoc: github://MallocArray/airgradient_esphome/packages/sensor_sgp41.yaml
  airgradient_api: github://MallocArray/airgradient_esphome/packages/airgradient_api_esp32-c3.yaml
  hardware_watchdog: github://MallocArray/airgradient_esphome/packages/watchdog.yaml
  wifi: github://MallocArray/airgradient_esphome/packages/sensor_wifi.yaml
  uptime: github://MallocArray/airgradient_esphome/packages/sensor_uptime.yaml
