---
# Office Workbench Lights
<<: !include common/diagnostics.yaml

esphome:
  name: office-workbench-lights
  friendly_name: 'Office Workbench Lights'

esp8266:
  board: esp01_1m

wifi: !include common/wifi.yaml

captive_portal:

# Enable logging
logger:

api:

ota:
  password: !secret esphome_ota

light:
  - platform: rgb
    id: 'office_workbench_lights'
    name: 'Office Workbench Lights'
    red: red_channel
    green: green_channel
    blue: blue_channel
    effects:
      - random:
          name: 'Slow Random Colors'
          transition_length: 30s
          update_interval: 30s
      - random:
          name: 'Fast Random Colors'
          transition_length: 4s
          update_interval: 5s
      - strobe:
          name: In Alarm
          colors:
            - state: true
              brightness: 100%
              red: 100%
              blue: 0%
              green: 0%
              duration: 150ms
            - state: false
              duration: 100ms
            - state: true
              brightness: 100%
              red: 100%
              blue: 0%
              green: 0%
              duration: 150ms
            - state: false
              duration: 100ms
            - state: true
              brightness: 100%
              red: 0%
              blue: 100%
              green: 0%
              duration: 150ms
            - state: false
              duration: 100ms
            - state: true
              brightness: 100%
              red: 0%
              blue: 100%
              green: 0%
              duration: 150ms
            - state: false
              duration: 100ms

output:
  - platform: esp8266_pwm
    id: red_channel
    pin: GPIO5
  - platform: esp8266_pwm
    id: green_channel
    pin: GPIO12
  - platform: esp8266_pwm
    id: blue_channel
    pin: GPIO13
