---
# Office Air Quality Sensor
<<: !include common/diagnostics.yaml

esphome:
  name: office-air-quality-sensor
  friendly_name: 'Office Air Quality Sensor'

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

wifi: !include common/wifi.yaml

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret home_assistant_api_encryption_key

ota:
  password: !secret esphome_ota

captive_portal:

# Enable active Bluetooth proxy
bluetooth_proxy:
  active: true

uart:
  # D2 = IO22
  rx_pin: GPIO22
  baud_rate: 9600

sensor:
  - platform: pm1006
    pm_2_5:
      id: 'office_air_quality'
      name: 'Office Air Quality'

###############################################################################
# I got this microphone arm for my office, and it has an LED. The controller
# sucked, so I replaced it with an ESP.
# https://gatorframeworks.com/products/broadcast-boom-mic-stand-with-led-indicator-light-gfwmicbcbm4000/
###############################################################################

# Configuration entry
light:
  - platform: monochromatic
    name: 'Office Microphone Light (Red)'
    output: output_red
  - platform: monochromatic
    name: 'Office Microphone Light (Blue)'
    output: output_blue

# Output entry
output:
  - platform: ledc
    id: output_red
    # D5 = IO18
    pin: GPIO18
    inverted: true
  - platform: ledc
    id: output_blue
    # D6 = IO19
    pin: GPIO19
    inverted: true
