---
substitutions:
  name: office-desk-controller
  friendly_name: Office Desk Controller
packages:
  # renovate: datasource=github-tags depName=tjhorner/upsy-desky
  tj_horner.upsy_desky: github://tjhorner/upsy-desky/firmware/stock.yaml@v4.0.0
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
wifi: !include common/wifi.yaml

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret home_assistant_api_encryption_key

ota:
  platform: esphome
  password: !secret esphome_ota

captive_portal:
