---
# Office Microphone Light
###############################################################################
# I got this microphone arm for my office, and it has an LED. The controller
# sucked, so I replaced it with an ESP.
# https://gatorframeworks.com/products/broadcast-boom-mic-stand-with-led-indicator-light-gfwmicbcbm4000/
###############################################################################

esphome:
  name: office_microphone_light
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret esphome_wifi_ssid
  password: !secret esphome_wifi_password
  domain: !secret esphome_domain
  fast_connect: !secret esphome_fast_connect
  power_save_mode: none

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret esphome_office_microphone_light_ssid
    password: !secret esphome_office_microphone_light_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_api

ota:
  password: !secret esphome_ota

# Configuration entry
light:
  - platform: monochromatic
    name: 'Office Microphone Light (Red)'
    output: output_red
  - platform: monochromatic
    name: 'Office Microphone Light (Blue)'
    output: output_blue

# Output entry
output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO05 # D1
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO04 # D2
