---
substitutions:
  name: master-bed-remote
  friendly_name: Primary Bedroom Remote
  room: Primary Bedroom
  dns_domain: !secret esphome_domain
  # renovate: datasource=github-releases depName=athom-tech/esp32-configs versioning=loose
  version: esphome-2026.7.3

packages:
  Athom_Technology.RF_IR_Remote: github://athom-tech/esp32-configs/athom-rf-ir-remote.yaml@${version}

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  area: ${room}

api:
  encryption:
    key: !secret home_assistant_api_encryption_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret esphome_domain
