---
substitutions:
  name: upstairs-hvac-uv
  device_name: upstairs-hvac-uv
  friendly_name: 'Upstairs HVAC UV'
  relay_restore_mode: RESTORE_DEFAULT_ON
packages:
  athom.smart-plug-v2: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml
  wifi: !include common/wifi.yaml
esphome:
  name_add_mac_suffix: false
api:
  encryption:
    key: !secret home_assistant_api_encryption_key
