### Energy ###
---
switch:
  - platform: group
    name: Energy - Heavy Consumers
    entities:
      - switch.dishwasher_outlet

input_number:
  solar_threshold:
    name: Solar Threshold
    icon: mdi:solar
    min: 500
    max: 2500
    step: 100
    unit_of_measurement: W

template:
  - binary_sensor:
      - default_entity_id: binary_sensor.solar_production
        name: Solar Production
        state: >
          {% if states('sensor.solaredge_ac_power')|float >
                states('input_number.solar_threshold')|float %}
            on
          {% else %}
            off
          {% endif %}

automation:
  - id: function_energy_solar_production
    alias: Function - Energy - Solar Production
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.solar_production
    action:
      - alias: Turn on outlets when solar is being produced
        service: >-
          {% if states('binary_sensor.solar_production') == 'on' %}
            script.energy_enable_heavy_consumption
          {% else %}
            script.energy_disable_heavy_consumption
          {% endif %}

script:
  energy_enable_heavy_consumption:
    alias: 'Energy - Enable Heavy Consumption'
    sequence:
      - alias: 'Debug notification'
        service: notify.notify
        data:
          message: 'Solar threshold exceeded'
      - alias: 'Enable heavy consumers'
        service: switch.turn_on
        target:
          entity_id: group.energy_heavy_consumers
  energy_disable_heavy_consumption:
    alias: 'Energy - Disable Heavy Consumption'
    sequence:
      - alias: 'Debug notification'
        service: notify.notify
        data:
          message: 'Solar insufficient'
      - alias: 'Disable heavy consumers'
        service: switch.turn_off
        target:
          entity_id: switch.energy_heavy_consumers
