### Energy ###
---
switch:
  - platform: group
    name: Energy - Heavy Consumers
    entities:
      - switch.dishwasher_outlet

input_number:
  solar_threshold:
    name: Solar Threshold
    icon: mdi:solar
    min: 500
    max: 2500
    step: 100
    unit_of_measurement: W

binary_sensor:
  - platform: template
    sensors:
      # This sensor will turn on when the solar array is generating >= 1kw
      solar_production:
        friendly_name: 'Solar Production'
        value_template: >-
          {% if states('sensor.solaredge_ac_power')|float >
                states('input_number.solar_threshold')|float %}
            on
          {% else %}
            off
          {% endif %}

automation:
  - id: function_energy_solar_production
    alias: Function - Energy - Solar Production
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.solar_production
    actions:
      - alias: Turn on outlets when solar is being produced
        action: >-
          {% if states('binary_sensor.solar_production') == 'on' %}
            script.energy_enable_heavy_consumption
          {% else %}
            script.energy_disable_heavy_consumption
          {% endif %}

script:
  energy_enable_heavy_consumption:
    alias: 'Energy - Enable Heavy Consumption'
    sequence:
      - alias: 'Debug notification'
        action: notify.notify
        data:
          message: 'Solar threshold exceeded'
      - alias: 'Enable heavy consumers'
        action: switch.turn_on
        target:
          entity_id: group.energy_heavy_consumers
  energy_disable_heavy_consumption:
    alias: 'Energy - Disable Heavy Consumption'
    sequence:
      - alias: 'Debug notification'
        action: notify.notify
        data:
          message: 'Solar insufficient'
      - alias: 'Disable heavy consumers'
        action: switch.turn_off
        target:
          entity_id: switch.energy_heavy_consumers
