### Presence Detection Functionality ###

homeassistant:
  customize:
    binary_sensor.vacancy:
      friendly_name: Empty House

group:
################################################################################
  vacation_settings:
    name: Vacation
    control: hidden
    entities:
      - input_boolean.vacation_ian
      - input_boolean.vacation_aimee
################################################################################
  network_phones:
    name: Phones
    entities:
      - device_tracker.network_aimees_iphone
      - device_tracker.network_ians_iphone
################################################################################

# The Bayesian sensor has been a real bitch to wrap my head around.
# One extremely valuable resource has been robmarkcole's Jupityr notebook.
# http://nbviewer.jupyter.org/github/robmarkcole/HASS-data-science/blob/master/Bayesian%20sensor%20tutorial.ipynb

binary_sensor:
################################################################################
  - platform: bayesian
    prior: 0.50 # The initial probability that the house is empty
    name: 'vacancy'
    probability_threshold: 0.75
    observations:
      - entity_id: 'device_tracker.network_ians_iphone'
        prob_given_true: 0.5
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'not_home'
      - entity_id: 'device_tracker.network_aimees_iphone'
        prob_given_true: 0.5
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'not_home'
################################################################################

################################################################################
  - platform: bayesian
    prior: 0.50 # The initial probability that the house is full
    name: 'occupancy'
    probability_threshold: 0.75
    observations:
      - entity_id: 'device_tracker.network_ians_iphone'
        prob_given_true: 0.9 
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.network_aimees_iphone'
        prob_given_true: 0.9
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'home'
      - entity_id: 'input_boolean.vacation_ian'
        prob_given_true: 0.9
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'on'
      - entity_id: 'input_boolean.vacation_aimee'
        prob_given_true: 0.9
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'on'
################################################################################

input_boolean:
################################################################################
  vacation_ian:
    name: 'Vacation - Ian'
    initial: off
    icon: mdi:beach
  vacation_aimee:
    name: 'Vacation - Aimee'
    initial: off
    icon: mdi:beach
################################################################################

automation:
################################################################################
  - id: function_presence_home
    alias: "Function - Presence - Home"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: 
        - device_tracker.network_ians_iphone
        - device_tracker.network_aimees_iphone
        to: 'home'
    condition:
      condition: or
      conditions:
      - condition: state
        entity_id: device_tracker.network_ians_iphone
        state: 'not_home'
      - condition: state
        entity_id: device_tracker.network_aimees_iphone
        state: 'not_home'
    action:
      service: script.location_home
################################################################################

################################################################################
  - id: function_presence_away
    alias: "Function - Presence - Away"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: 
        - device_tracker.network_ians_iphone
        - device_tracker.network_aimees_iphone
        to: 'not_home'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: device_tracker.network_ians_iphone
        state: 'not_home'
      - condition: state
        entity_id: device_tracker.network_aimees_iphone
        state: 'not_home'
    action:
      service: script.location_away
################################################################################

################################################################################
  - id: test_person
    alias: "Test - Person Component"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: 
        - person.ian
        - person.aimee
    action:
      - service: notify.notify
        data:
          message: >
            Person Component Triggered: {{ trigger.entity_id }} 
################################################################################

scene:
################################################################################
  - name: Home
    entities:
      alarm_control_panel.home: 'disarmed'
      climate.downstairs: 'home'
################################################################################

################################################################################
  - name: Away
    entities:
      alarm_control_panel.home: 'armed_away'
      climate.downstairs: 'away'
################################################################################

# Scripts
script:
################################################################################
  location_away:
    alias: 'Function - Presence - Away'
    sequence:
      # Turn everything off (Call scene)
      # Turn the thermostat off
      - service: nest.set_away_mode
        data:
          away_mode: away
      # Arm the alarm
      - service: alarm_control_panel.alarm_arm_away
        data:
          entity_id: alarm_control_panel.home
          code: !secret alarm_code
      # Randomly turn on and off lights to simulate occupancy
      # TODO
################################################################################
  location_home:
    alias: 'Function - Presence - Home'
    sequence:
      # Turn everything back on (Call scene)
      # Turn the thermostat back on
      - service: nest.set_away_mode
        data:
          away_mode: home
      # Disarm the alarm
      - service: alarm_control_panel.alarm_disarm
        data:
          entity_id: alarm_control_panel.home
          code: !secret alarm_code
################################################################################
