---
### HVAC Functions ###

input_number:
  hvac_uv_power_threshold:
    name: HVAC UV Power Threshold
    icon: mdi:flash
    min: 0
    max: 50
    step: 5
    unit_of_measurement: Watts
  hvac_co2_threshold:
    name: HVAC CO2 Threshold
    icon: mdi:air-filter
    min: 0
    max: 2000
    step: 100
    unit_of_measurement: ppm

template:
  - binary_sensor:
      - default_entity_id: binary_sensor.downstairs_hvac_uv
        name: Downstairs HVAC UV
        state: >
          {% if states.sensor.downstairs_hvac_uv_power.state == 'unavailable' %}
            off
          {% else %}
            {{ ( float(states.sensor.downstairs_hvac_uv_power.state) >
                float(states.input_number.hvac_uv_power_threshold.state) ) }}
          {% endif %}
      - default_entity_id: binary_sensor.upstairs_hvac_uv
        name: Upstairs HVAC UV
        state: >
          {% if states.sensor.upstairs_hvac_uv_power.state == 'unavailable' %}
            off
          {% else %}
            {{ ( float(states.sensor.upstairs_hvac_uv_power.state) >
                float(states.input_number.hvac_uv_power_threshold.state) ) }}
          {% endif %}
      - default_entity_id: binary_sensor.downstairs_co2_high
        name: Downstairs CO2 High
        state: >
          {{ ( float(states.sensor.downstairs_air_quality_sensor_co2.state) >
              float(states.input_number.hvac_co2_threshold.state) ) }}
      - default_entity_id: binary_sensor.upstairs_co2_high
        name: Upstairs CO2 High
        state: >
          {{ ( float(states.sensor.upstairs_air_quality_sensor_co2.state) >
              float(states.input_number.hvac_co2_threshold.state) ) }}

automation:
  #############################################################################
  # keep both HVAC units set temperature synchronized
  - id: function_hvac_sync
    alias: 'Function - HVAC Sync'
    trigger:
      - platform: state
        entity_id:
          - climate.homekit_downstairs
          - climate.homekit_upstairs
    action:
      - alias: 'State Handler'
        choose:
          - conditions:
              alias: Upstairs was changed
              condition: template
              value_template: >
                {{ trigger.entity_id == 'climate.homekit_upstairs' }}
            sequence:
              service: climate.set_temperature
              target:
                entity_id: climate.homekit_downstairs
              data:
                temperature: >
                  {{ state_attr('climate.homekit_upstairs', 'temperature') }}
                hvac_mode: >
                  {{ states.climate.homekit_upstairs.state }}
          - conditions:
              alias: Downstairs was changed
              condition: template
              value_template: >
                {{ trigger.entity_id == 'climate.homekit_downstairs' }}
            sequence:
              service: climate.set_temperature
              target:
                entity_id: climate.homekit_upstairs
              data:
                temperature: >
                  {{ state_attr('climate.homekit_downstairs', 'temperature') }}
                hvac_mode: >
                  {{ states.climate.homekit_downstairs.state }}
  #############################################################################
  # Turn off HVAC if an outside door has been left open for 60 seconds
  - id: function_hvac_efficiency_doors
    alias: Function - HVAC - Efficency (Doors)
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.front_door
          - binary_sensor.back_door
          - binary_sensor.garage_door
        from: 'closed'
        to: 'open'
        for:
          seconds: 60
      - platform: state
        entity_id:
          - binary_sensor.front_door
          - binary_sensor.back_door
          - binary_sensor.garage_door
        from: 'open'
        to: 'closed'
    action:
      - alias: 'State Handler'
        choose:
          - conditions:
              - alias: 'Door Open'
                condition: template
                value_template: "{{ trigger.to_state == 'open' }}"
            sequence:
              - alias: 'Turn off HVAC'
                service: climate.turn_off
                target:
                  entity_id:
                    - climate.homekit_downstairs
                    - climate.homekit_upstairs
          - conditions:
              - alias: 'Door Closed'
                condition: template
                value_template: "{{ trigger.to_state == 'closed' }}"
            sequence:
              - alias: 'Turn on HVAC'
                service: climate.turn_on
                target:
                  entity_id:
                    - climate.homekit_downstairs
                    - climate.homekit_upstairs
  ################################################################################
  - id: function_hvac_downstairs_uv_alert
    alias: Function - HVAC - Downstairs UV Alert
    trigger:
      platform: state
      entity_id: climate.homekit_downstairs
      to: 'on'
      for: '00:01:00'
    condition:
      condition: state
      entity_id: binary_sensor.downstairs_hvac_uv
      state: 'off'
    action:
      - service: notify.notify
        data:
          message: 'Downstairs HVAC UV bulb may be burnt out!'
  ################################################################################
  - id: function_hvac_upstairs_uv_alert
    alias: Function - HVAC - Downstairs UV Alert
    trigger:
      platform: state
      entity_id: climate.homekit_upstairs
      to: 'on'
      for: '00:01:00'
    condition:
      condition: state
      entity_id: binary_sensor.upstairs_hvac_uv
      state: 'off'
    action:
      - service: notify.notify
        data:
          message: 'Upstairs HVAC UV bulb may be burnt out!'
  ################################################################################
  - id: function_hvac_co2
    alias: Function - HVAC - CO2
    description: Turn on the HVAC fan if CO2 reaches > 500 ppm
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.downstairs_co2_high
          - binary_sensor.upstairs_co2_high
    action:
      choose:
        - conditions:
            - alias: Downstairs CO2
              condition: template
              value_template: >
                {{ trigger.entity_id == 'binary_sensor.downstairs_co2_high' }}
          sequence:
            - choose:
                - conditions:
                    - alias: Downstairs CO2 High
                      condition: state
                      entity_id: binary_sensor.downstairs_co2_high
                      state: 'on'
                  sequence:
                    - alias: Turn on Downstairs HVAC fan
                      service: climate.set_fan_mode
                      target:
                        entity_id: climate.homekit_downstairs
                      data:
                        fan_mode: 'on'
                - conditions:
                    - alias: Downstairs CO2 Low
                      condition: state
                      entity_id: binary_sensor.downstairs_co2_high
                      state: 'off'
                  sequence:
                    - alias: Turn off Downstairs HVAC fan
                      service: climate.set_fan_mode
                      target:
                        entity_id: climate.homekit_downstairs
                      data:
                        fan_mode: auto
        - conditions:
            - alias: Upstairs CO2
              condition: template
              value_template: >
                {{ trigger.entity_id == 'binary_sensor.upstairs_co2_high' }}
          sequence:
            - choose:
                - conditions:
                    - alias: Upstairs CO2 High
                      condition: state
                      entity_id: binary_sensor.upstairs_co2_high
                      state: 'on'
                  sequence:
                    - alias: Turn on Upstairs HVAC fan
                      service: climate.set_fan_mode
                      target:
                        entity_id: climate.homekit_upstairs
                      data:
                        fan_mode: 'on'
                - conditions:
                    - alias: Upstairs CO2 Low
                      condition: state
                      entity_id: binary_sensor.upstairs_co2_high
                      state: 'off'
                  sequence:
                    - alias: Turn off Upstairs HVAC fan
                      service: climate.set_fan_mode
                      target:
                        entity_id: climate.homekit_upstairs
                      data:
                        fan_mode: auto
################################################################################
