---
### HVAC Functions ###

input_number:
  hvac_uv_power_threshold:
    name: HVAC UV Power Threshold
    icon: mdi:flash
    min: 0
    max: 50
    step: 5
    unit_of_measurement: Watts

binary_sensor:
  - platform: template
    sensors:
      downstairs_hvac_uv:
        friendly_name: 'Downstairs HVAC UV'
        value_template: >
          {% if states.sensor.downstairs_hvac_uv_power.state == 'unavailable' %}
            off
          {% else %}
            {{ ( float(states.sensor.downstairs_hvac_uv_power.state)
              > float(states.input_number.hvac_uv_power_threshold.state) ) }}
          {% endif %}
  - platform: template
    sensors:
      upstairs_hvac_uv:
        friendly_name: 'Upstairs HVAC UV'
        value_template: >
          {% if states.sensor.upstairs_hvac_uv_power.state == 'unavailable' %}
            off
          {% else %}
            {{ ( float(states.sensor.upstairs_hvac_uv_power.state)
              > float(states.input_number.hvac_uv_power_threshold.state) ) }}
          {% endif %}

automation:
  #############################################################################
  # keep both HVAC units set temperature synchronized
  - id: function_hvac_sync
    alias: 'Function - HVAC Sync'
    trigger:
      - platform: state
        entity_id:
          - climate.homekit_downstairs
          - climate.homekit_upstairs
    action:
      - alias: 'State Handler'
        choose:
          - conditions:
              alias: Upstairs was changed
              condition: template
              value_template: >
                {{ trigger.entity_id == 'climate.homekit_upstairs' }}
            sequence:
              service: climate.set_temperature
              target:
                entity_id: climate.homekit_downstairs
              data:
                temperature: >
                  {{ state_attr('climate.homekit_upstairs', 'temperature') }}
                hvac_mode: >
                  {{ states.climate.homekit_upstairs.state }}
          - conditions:
              alias: Downstairs was changed
              condition: template
              value_template: >
                {{ trigger.entity_id == 'climate.homekit_downstairs' }}
            sequence:
              service: climate.set_temperature
              target:
                entity_id: climate.homekit_upstairs
              data:
                temperature: >
                  {{ state_attr('climate.homekit_downstairs', 'temperature') }}
                hvac_mode: >
                  {{ states.climate.homekit_downstairs.state }}
  #############################################################################
  # Turn off HVAC if an outside door has been left open for 60 seconds
  - id: function_hvac_efficiency_doors
    alias: Function - HVAC - Efficency (Doors)
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.front_door
          - binary_sensor.back_door
          - binary_sensor.garage_door
        from: 'closed'
        to: 'open'
        for:
          seconds: 60
      - platform: state
        entity_id:
          - binary_sensor.front_door
          - binary_sensor.back_door
          - binary_sensor.garage_door
        from: 'open'
        to: 'closed'
    action:
      - alias: 'State Handler'
        choose:
          - conditions:
              - alias: 'Door Open'
                condition: template
                value_template: "{{ trigger.to_state == 'open' }}"
            sequence:
              - alias: 'Turn off HVAC'
                service: climate.turn_off
                target:
                  entity_id:
                    - climate.homekit_downstairs
                    - climate.homekit_upstairs
          - conditions:
              - alias: 'Door Closed'
                condition: template
                value_template: "{{ trigger.to_state == 'closed' }}"
            sequence:
              - alias: 'Turn on HVAC'
                service: climate.turn_on
                target:
                  entity_id:
                    - climate.homekit_downstairs
                    - climate.homekit_upstairs
  ################################################################################
  - id: function_hvac_downstairs_uv_alert
    alias: Function - HVAC - Downstairs UV Alert
    trigger:
      platform: state
      entity_id: climate.homekit_downstairs
      to: 'on'
      for: '00:01:00'
    condition:
      condition: state
      entity_id: binary_sensor.downstairs_hvac_uv
      state: 'off'
    action:
      - service: notify.notify
        data:
          message: 'Downstairs HVAC UV bulb may be burnt out!'
  ################################################################################
  - id: function_hvac_upstairs_uv_alert
    alias: Function - HVAC - Downstairs UV Alert
    trigger:
      platform: state
      entity_id: climate.homekit_upstairs
      to: 'on'
      for: '00:01:00'
    condition:
      condition: state
      entity_id: binary_sensor.upstairs_hvac_uv
      state: 'off'
    action:
      - service: notify.notify
        data:
          message: 'Upstairs HVAC UV bulb may be burnt out!'
################################################################################
