---
################################################################################
# Function - Security
################################################################################

# This is currently very rudimentary, but the goal is to start integrating
# additional sensors into my alarm system, and provide a better means of
# monitoring the house when we are away.
# Ideas:
# Flash some lights/make some noise when the alarm is tripped
# Make a wife idicator light for when the alarm is armed
# integrate external sensors into the alarm

################################################################################
# Inputs
################################################################################
input_datetime:
  alarm_auto_arm:
    name: 'Alarm Auto-Arm'
    icon: mdi:clock-outline
    has_date: false
    has_time: true

  alarm_auto_disarm:
    name: 'Alarm Auto-Disarm'
    icon: mdi:clock-outline
    has_date: false
    has_time: true
################################################################################

################################################################################
# iOS Notifications
################################################################################
# ios:
#   push:
#     categories:
#       - name: Garage Door
#         identifier: 'garage_door'
#         actions:
#           - identifier: 'garage_close'
#             title: 'Close'
#             activationMode: 'background'
#             authenticationRequired: true
#             destructive: false
#             behavior: 'default'
#           - identifier: 'dismiss'
#             title: 'Dismiss'
#             activationMode: 'background'
#             authenticationRequired: true
#             destructive: true
#             behavior: 'default'
################################################################################

sensor:
  ################################################################################
  - platform: template
    sensors:
      alarm_auto_arm:
        friendly_name: 'Alarm Auto Arm'
        icon_template: mdi:clock-outline
        # entity_id: input_datetime.alarm_auto_arm
        value_template: >
          {{ (states.input_datetime.alarm_auto_arm.attributes.timestamp | 
              int | timestamp_custom("%H:%M",False)) }}
      alarm_auto_disarm:
        friendly_name: 'Alarm Auto Disarm'
        icon_template: mdi:clock-outline
        # entity_id: input_datetime.alarm_auto_disarm
        value_template: >
          {{ (states.input_datetime.alarm_auto_disarm.attributes.timestamp | 
              int | timestamp_custom("%H:%M",False)) }}
################################################################################
automation:
  ################################################################################
  # Watch the following sensors when the alarm is on to extend the system
  - id: function_security_additional_sensors
    alias: 'Function - Security - Additional Sensors'
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.garage_motion
          - binary_sensor.garage_side_door
    condition:
      - condition: state
        entity_id:
          - alarm_control_panel.home
        state:
          - armed
          - armed_home
    action:
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.home
  ################################################################################
  - id: function_security_alarm_auto_arm
    alias: 'Function - Security - Alarm Auto Arm'
    trigger:
      - platform: template
        value_template: >
          {{ states.sensor.time.state == states.sensor.alarm_auto_arm.state }}
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.worknight
          state: 'on'
        - condition: state
          entity_id: input_boolean.away_mode
          state: 'off'
    action:
      service: alarm_control_panel.alarm_arm_home
      data:
        entity_id: alarm_control_panel.home
        code: !secret alarm_code
  ################################################################################
  - id: function_security_alarm_auto_disarm
    alias: 'Function - Security - Alarm Auto Disarm'
    trigger:
      - platform: template
        value_template: >
          {{ states.sensor.time.state == states.sensor.alarm_auto_disarm.state }}
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.workday
          state: 'on'
        - condition: state
          entity_id: input_boolean.away_mode
          state: 'off'
    action:
      service: alarm_control_panel.alarm_disarm
      data:
        entity_id: alarm_control_panel.home
        code: !secret alarm_code
  ################################################################################
  - id: function_security_front_porch_motion
    alias: 'Function - Security - Front Porch Motion'
    trigger:
      - platform: state
        entity_id: binary_sensor.front_porch_motion
        from: 'off'
        to: 'on'
    action:
      # Send an alert to all users
      - service: notify.notify
        data:
          title: 'Motion detected at front door'
          message: 'Who could it be?'
  # TODO:
  # - Send a snapshot from the front porch camera
  # - Make this an actionable notification to start a video call
  ################################################################################
  - id: function_security_alarm_armed
    alias: 'Function - Security - Alarm Armed'
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home
        from: 'disarmed'
        to:
          - 'armed'
          - 'armed_home'
    action:
      # Send an alert to all users
      - service: script.notification_alarm_armed
  ################################################################################
  - id: function_security_alarm_disarmed
    alias: 'Function - Security - Alarm Disarmed'
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home
        from:
          - 'armed'
          - 'armed_home'
        to: 'disarmed'
    action:
      # Send an alert to all users
      - service: script.notification_alarm_disarmed
  ################################################################################
  - id: function_security_alarm_warning
    alias: 'Function - Security - Alarm Warning'
    trigger:
      - platform: state
        entity_id: lock.back_door
        from: 'locked'
        to: 'unlocked'
    condition:
      - condition: state
        entity_id: alarm_control_panel.home
        state: 'armed_home'
    action:
      # Send an alert to all users
      - service: script.notification_alarm_armed
  ################################################################################
  - id: function_security_garage
    alias: 'Function - Security - Garage'
    trigger:
      - platform: state
        entity_id:
          - cover.main_garage_door
          - cover.second_garage_door
        from: closed
        to: open
        for: 00:05:00
    condition:
      - condition: state
        entity_id: input_boolean.away_mode
        # state: 'on'
        # Condition override for testing purposes
        state: 'off'
    action:
      - service: notify.mobile_app_ians_iphone
        data:
          title: 'Garage Open!'
          message: 'The {{ trigger.name }} has been left open. What would you like to do?'
          data:
            push:
              category: 'garage_door'
            action_data:
              entity_id: >
                {{ trigger.entity_id }}
      - wait_for_trigger:
          platform: event
          event_type: ios.notification_action_fired
################################################################################

script:
  ################################################################################
  notification_alarm_armed:
    alias: 'Notification - Alarm Armed'
    sequence:
      - service: media_player.volume_set
        entity_id:
          - media_player.downstairs_thermostat
          - media_player.upstairs_thermostat
          - media_player.ian_s_echo_dot
        data:
          volume_level: '1.0'
      - service: notify.alexa_media
        data:
          data:
            type: tts
          target:
            - media_player.downstairs_thermostat
            - media_player.upstairs_thermostat
            - media_player.ian_s_echo_dot
          message: 'The alarm is armed.'
  ################################################################################
  notification_alarm_disarmed:
    alias: 'Notification - Alarm Disarmed'
    sequence:
      - service: media_player.volume_set
        entity_id:
          - media_player.downstairs_thermostat
          - media_player.upstairs_thermostat
          - media_player.ian_s_echo_dot
        data:
          volume_level: '1.0'
      - service: notify.alexa_media
        data:
          data:
            type: tts
          target:
            - media_player.downstairs_thermostat
            - media_player.upstairs_thermostat
            - media_player.ian_s_echo_dot
          message: 'The alarm is disarmed.'
  ################################################################################
