################################################################################
# Function - Security
################################################################################

# This is currently very rudimentary, but the goal is to start integrating
# additional sensors into my alarm system, and provide a better means of
# monitoring the house when we are away.

automation:
################################################################################
  - id: function_security_front_porch_motion
    alias: 'Function - Security - Front Porch Motion'
    # initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.front_porch_motion
        from: 'off'
        to: 'on'
    action:
  # Send an alert to all users
      - service: notify.notify
        data:
          title: "Motion detected at front door"
          message: "Who could it be?"
  # TODO: 
  # - Send a snapshot from the front porch camera
  # - Make this an actionable notification to start a video call
################################################################################