---
################################################################################
# Function - Security
################################################################################

# This is currently very rudimentary, but the goal is to start integrating
# additional sensors into my alarm system, and provide a better means of
# monitoring the house when we are away.
# Ideas:
# Flash some lights/make some noise when the alarm is tripped
# integrate external sensors into the alarm

################################################################################
# Inputs
################################################################################
input_datetime:
  alarm_auto_arm:
    name: 'Alarm Auto-Arm'
    icon: mdi:clock-outline
    has_date: false
    has_time: true

  alarm_auto_disarm:
    name: 'Alarm Auto-Disarm'
    icon: mdi:clock-outline
    has_date: false
    has_time: true
################################################################################

################################################################################
# iOS Notifications
################################################################################
# ios:
#   push:
#     categories:
#       - name: Garage Door
#         identifier: 'garage_door'
#         actions:
#           - identifier: 'garage_close'
#             title: 'Close'
#             activationMode: 'background'
#             authenticationRequired: true
#             destructive: false
#             behavior: 'default'
#           - identifier: 'dismiss'
#             title: 'Dismiss'
#             activationMode: 'background'
#             authenticationRequired: true
#             destructive: true
#             behavior: 'default'
################################################################################

sensor:
  ################################################################################
  - platform: template
    sensors:
      alarm_auto_arm:
        friendly_name: 'Alarm Auto Arm'
        icon_template: mdi:clock-outline
        # entity_id: input_datetime.alarm_auto_arm
        value_template: >
          {{ (states.input_datetime.alarm_auto_arm.attributes.timestamp |
              int | timestamp_custom("%H:%M",False)) }}
      alarm_auto_disarm:
        friendly_name: 'Alarm Auto Disarm'
        icon_template: mdi:clock-outline
        # entity_id: input_datetime.alarm_auto_disarm
        value_template: >
          {{ (states.input_datetime.alarm_auto_disarm.attributes.timestamp |
              int | timestamp_custom("%H:%M",False)) }}
################################################################################
automation:
  ################################################################################
  - id: function_security_alarm_state_change
    alias: 'Function - Security - Alarm State Change'
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home
    action:
      - variables:
          color: > # red, green, blue
            {% if trigger.to_state.state == 'armed_away' %}
              0
            {% elif trigger.to_state.state in ['armed_home', 'armed_night'] %}
              85
            {% else %}
              170
            {% endif %}
      - choose:
          - conditions:
              - condition: template
                value_template: >
                  {{ trigger.to_state.state in ['armed', 'armed_home', 'armed_away'] }}
            sequence:
              - alias: 'Lock all doors'
                service: lock.lock
                entity_id:
                  - lock.front_door_lock
                  - lock.back_door_lock
              - alias: 'Close all covers'
                service: cover.close_cover
                entity_id:
                  - cover.main_garage_door
                  - cover.second_garage_door
              - alias: 'Turn off fireplace'
                service: switch.turn_off
                target:
                  entity_id: switch.fireplace
      - alias: 'Get all switch LED indicators'
        variables:
          lights: >
            {{ states.number
                | selectattr('entity_id', 'search', '_led_indicator_color$')
                | map(attribute='entity_id')
                | list }}
      - alias: 'Cycle through all lights'
        repeat:
          for_each: >
            {{ lights }}
          sequence:
            - alias: 'Set switch indicator to color'
              service: number.set_value
              data:
                entity_id: >
                  {{ repeat.item }}
                value: >
                  {{ color }}
  ################################################################################
  # Watch the following sensors when the alarm is on to extend the system
  - id: function_security_additional_sensors
    alias: 'Function - Security - Additional Sensors'
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.garage_side_door
    condition:
      - condition: state
        entity_id:
          - alarm_control_panel.home
        state:
          - armed
          - armed_home
    action:
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.home
  ################################################################################
  - id: function_security_alarm_auto_arm
    alias: 'Function - Security - Alarm Auto Arm'
    trigger:
      - platform: template
        value_template: >
          {{ states.sensor.time.state == states.sensor.alarm_auto_arm.state }}
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.worknight
          state: 'on'
    action:
      service: alarm_control_panel.alarm_arm_home
      data:
        entity_id: alarm_control_panel.home
        code: !secret alarm_code
  ################################################################################
  - id: function_security_alarm_auto_disarm
    alias: 'Function - Security - Alarm Auto Disarm'
    trigger:
      - platform: template
        value_template: >
          {{ states.sensor.time.state == states.sensor.alarm_auto_disarm.state }}
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.workday
          state: 'on'
        - condition: state
          entity_id: input_boolean.away_mode
          state: 'off'
        - condition: state
          entity_id: input_boolean.vacation_mode
          state: 'off'
    action:
      service: alarm_control_panel.alarm_disarm
      data:
        entity_id: alarm_control_panel.home
        code: !secret alarm_code
  ################################################################################
  - id: function_security_front_porch_motion
    alias: 'Function - Security - Front Porch Motion'
    trigger:
      - platform: state
        entity_id: binary_sensor.front_porch_motion
        from: 'off'
        to: 'on'
    action:
      # Send an alert to all users
      - service: notify.notify
        data:
          title: 'Motion detected at front door'
          message: 'Who could it be?'
          # TODO:
          # - Send a snapshot from the front porch camera
          # - Make this an actionable notification to start a video call
################################################################################
