### Presence Detection Functionality ###

homeassistant:
  customize:
    binary_sensor.vacancy:
      friendly_name: Empty House

# The Bayesian sensor has been a real bitch to wrap my head around.
# One extremely valuable resource has been robmarkcole's Jupityr notebook.
# http://nbviewer.jupyter.org/github/robmarkcole/HASS-data-science/blob/master/Bayesian%20sensor%20tutorial.ipynb

binary_sensor:
################################################################################
  - platform: bayesian
    prior: 0.50 # The initial probability that the house is empty
    name: 'vacancy'
    probability_threshold: 0.9
    observations:
      - entity_id: 'device_tracker.network_ians_iphone'
        prob_given_true: 0.9 
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'not_home'
      - entity_id: 'device_tracker.network_aimees_iphone'
        prob_given_true: 0.9
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'not_home'
      - entity_id: 'device_tracker.network_richards_iphone'
        prob_given_true: 0.9
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'not_home'
################################################################################

input_boolean:
  vacation_ian:
    name: 'Vacation - Ian'
    initial: off
    icon: mdi:beach
  vacation_aimee:
    name: 'Vacation - Aimee'
    initial: off
    icon: mdi:beach
  vacation_richard:
    name: 'Vacation - Richard'
    initial: off
    icon: mdi:beach

automation:
################################################################################
  - id: location_home
    alias: "Location - Home"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: 
        - device_tracker.network_ians_iphone
        - device_tracker.network_aimees_iphone
        - device_tracker.network_richards_iphone
        to: 'home'
    condition:
      condition: or
      conditions:
      - condition: state
        entity_id: device_tracker.network_ians_iphone
        state: 'not_home'
      - condition: state
        entity_id: device_tracker.network_aimees_iphone
        state: 'not_home'
      - condition: state
        entity_id: device_tracker.network_richards_iphone
        state: 'not_home'
    action:
  # Change this to a script later on
#      service: script.location_home
      - service: nest.set_mode
        data:
          home_mode: home
          structure:
            - Percivale
      - service: alarm_control_panel.alarm_disarm
        data:
          entity_id: alarm_control_panel.home
          code: !secret alarm_code
################################################################################

################################################################################
  - id: location_away
    alias: "Location - Away"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: 
        - device_tracker.network_ians_iphone
        - device_tracker.network_aimees_iphone
        - device_tracker.network_richards_iphone
        to: 'not_home'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: device_tracker.network_ians_iphone
        state: 'not_home'
      - condition: state
        entity_id: device_tracker.network_aimees_iphone
        state: 'not_home'
      - condition: state
        entity_id: device_tracker.network_richards_iphone
        state: 'not_home'
    action:
  # Change this to a script later on
#      service: script.location_away
      - service: nest.set_mode
        data:
          home_mode: away
          structure:
            - Percivale
      - service: alarm_control_panel.alarm_arm_away
        data:
          entity_id: alarm_control_panel.home
          code: !secret alarm_code
################################################################################

################################################################################
  - id: test_vacancy
    alias: "Test - Bayesian Vacancy"
    initial_state: 'off'
    trigger:
      - platform: state
        entity_id: 
        - binary_sensor.vacancy
    action:
      - service: notify.notify
        data:
          message: >
            Bayesian Vacancy Sensor Triggered: {{ states.binary_sensor.vacancy.state }}
################################################################################

scene:
################################################################################
  - name: Home
    entities:
      alarm_control_panel.home: 'disarmed'
      climate.downstairs: 'home'
################################################################################

################################################################################
  - name: Away
    entities:
      alarm_control_panel.home: 'armed_away'
      climate.downstairs: 'eco'
################################################################################

# Scripts
script:
################################################################################
  location_away:
    alias: 'Location - Away'
    sequence:
      # Turn everything off (Call scene)
      # Turn the thermostat off
      - service: nest.set_mode
        data:
          home_mode: away
          structure:
            - Percivale
      # Arm the alarm
      - service: alarm_control_panel.alarm_arm_away
        data:
          entity_id: alarm_control_panel.home
          code: !secret alarm_code
      # Randomly turn on and off lights to simulate occupancy
      # TODO
################################################################################
  location_home:
    alias: 'Location - Home'
    sequence:
      # Turn everything off (Call scene)
      # Turn the thermostat off
      - service: nest.set_mode
        data:
          home_mode: home
          structure:
            - Percivale
      # Arm the alarm
      - service: alarm_control_panel.alarm_disarm
        data:
          entity_id: alarm_control_panel.home
          code: !secret alarm_code
      # Randomly turn on and off lights to simulate occupancy
      # TODO
################################################################################
