### Presence Detection Functionality ###

binary_sensor:
################################################################################
  - platform: bayesian
    prior: 0.5
    name: 'Vacant'
    probability_threshold: 0.9
    observations:
      - entity_id: 'device_tracker.network_ians_iphone'
        prob_given_true: 0.9
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'not_home'
      - entity_id: 'device_tracker.network_aimees_iphone'
        prob_given_true: 0.9
        prob_given_false: 0.2
        platform: 'state'
        to_state: 'not_home'
      - entity_id: 'device_tracker.network_richards_iphone'
        prob_given_true: 0.9
        prob_given_false: 0.4
        platform: 'state'
        to_state: 'not_home'
################################################################################

automation:
################################################################################
  - id: location_home
    alias: "Location - Home"
    trigger:
      - platform: state
        entity_id: 
        - device_tracker.network_ians_iphone
        - device_tracker.network_aimees_iphone
        - device_tracker.network_richards_iphone
        to: 'home'
    condition:
      condition: or
      conditions:
      - condition: state
        entity_id: device_tracker.network_ians_iphone
        state: 'not_home'
      - condition: state
        entity_id: device_tracker.network_aimees_iphone
        state: 'not_home'
      - condition: state
        entity_id: device_tracker.network_richards_iphone
        state: 'not_home'
    action:
  # Change this to a scene later on
      - service: nest.set_mode
        data:
          home_mode: home
          structure:
            - Percivale
      - service: alarm_control_panel.alarm_disarm
        data:
          entity_id: alarm_control_panel.home
          code: !secret alarm_code
################################################################################

################################################################################
  - id: location_away
    alias: "Location - Away"
    trigger:
      - platform: state
        entity_id: 
        - device_tracker.network_ians_iphone
        - device_tracker.network_aimees_iphone
        - device_tracker.network_richards_iphone
        to: 'not_home'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: device_tracker.network_ians_iphone
        state: 'not_home'
      - condition: state
        entity_id: device_tracker.network_aimees_iphone
        state: 'not_home'
      - condition: state
        entity_id: device_tracker.network_richards_iphone
        state: 'not_home'
    action:
  # Change this to a scene later on
      - service: nest.set_mode
        data:
          home_mode: away
          structure:
            - Percivale
      - service: alarm_control_panel.alarm_arm_away
        data:
          entity_id: alarm_control_panel.home
          code: !secret alarm_code
################################################################################

################################################################################
  - id: test_vacancy
    alias: "Test - Bayesian Vacancy"
    trigger:
      - platform: state
        entity_id: 
        - binary_sensor.vacant
    action:
      - service: notify.notify
        data:
          message: >
            Bayesian Vacancy Sensor Triggered: {{ trigger.event.data.state }}
################################################################################

scene:
################################################################################
  - name: Home
    entities:
      alarm_control_panel.home: 'disarmed'
      climate.downstairs: 'home'
################################################################################

################################################################################
  - name: Away
    entities:
      alarm_control_panel.home: 'armed_away'
      climate.downstairs: 'eco'
################################################################################