################################################################################
# Function - Lighting
################################################################################

# This is to fix some of the wierd lighting issues. 

automation:
################################################################################
  - id: function_lighting_dining_room
    alias: "Function - Lighting - Dining Room"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: light.wink_dining_room
    condition:
      condition: 'and'
      conditions:
      - condition: state
        entity_id: light.wink_dining_room
        state: 'on'
      - condition: numeric_state
        entity_id: light.wink_dining_room
        below: '15'
    action:
    - data:
        brightness_pct: '20'
        entity_id: light.wink_dining_room
      service: light.turn_on
################################################################################