################################################################################
# Function - Lighting
################################################################################

# This is to fix some of the wierd lighting issues. 

automation:
################################################################################
  - id: function_lighting_dining_room
    alias: "Function - Lighting - Dining Room"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: light.wink_dining_room
    condition:
      condition: 'and'
      conditions:
      - condition: state
        entity_id: light.wink_dining_room
        state: 'on'
      - condition: numeric_state
        entity_id: light.wink_dining_room
        value_template: "{{ state.attributes.brightness }}"
        below: 38.25
    action:
    - service: light.turn_on
      data:
        entity_id: light.wink_dining_room
        brightness_pct: '20'
################################################################################

################################################################################
  - id: routine_night_front_door_motion_initial
    alias: 'Routine - Night - Front Porch Motion (Initial)'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.ring_front_door_motion
        from: 'off'
        to: 'on'
    condition:
      condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    action:
  # Transition to this profile, even if on
      - service: light.turn_on
        data:
          entity_id: light.front_porch_lights
          profile: energize
          transition: 1
################################################################################

################################################################################
  - id: routine_night_front_door_motion_idle
    alias: 'Routine - Night - Front Porch Motion (Idle)'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.ring_front_door_motion
        from: 'on'
        to: 'off'
        for:
          seconds: 150
    condition:
      condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    action:
  # Transition back to a preset profile/scene
    - service: light.turn_on
      data:
        entity_id: light.front_porch_lights
        profile: relax
        brightness_pct: 25
        transition: 5
################################################################################