## Wink ##

homeassistant:
  customize:
    sensor.wink_master_relay_temperature:
      friendly_name: Master Relay Temperature
    sensor.wink_master_relay_humidity:
      friendly_name: Master Relay Humidity
    binary_sensor.wink_master_relay_presence:
      friendly_name: Master Relay Presence
    sensor.wink_master_relay_proximity:
     friendly_name: Master Relay Proximity 
    switch.wink_overhead_light:
      icon: mdi:ceiling-light
    switch.wink_ceiling_fan:
      icon: mdi:fan
    light.wink_dining_room:
      hidden: false
      icon: mdi:ceiling-light
    # Duplicate objects
    binary_sensor.ring_front_door_motion:
      hidden: true
    binary_sensor.ring_front_door_ding:
      hidden: true
    binary_sensor.wink_gang:
      hidden: true
    binary_sensor.wink_front_door_button_pressed:
      hidden: true
    binary_sensor.wink_front_door_motion:
      hidden: true
    climate.wink_percivale_downstairs_thermostat:
      hidden: true
  customize_glob: 
    "light.wink_*":
      hidden: true

wink:
#  email: !secret wink_email
#  password: !secret wink_password
#  client_id: !secret wink_client_id
#  client_secret: !secret wink_client_secret
  local_control: false

# Binary Sensors
binary_sensor:
- platform: wink
  entity_namespace: wink

# Climate
climate:
- platform: wink
  entity_namespace: wink

# Lights
light:
- platform: wink
  entity_namespace: wink

# Sensors
sensor:
- platform: wink
  entity_namespace: wink

# Switch
switch:
- platform: wink
  entity_namespace: wink