### Roomba ###

# The majority of this has come from TheHookUp's YouTube channel
# https://www.youtube.com/watch?v=t2NgA8qYcFI

# HomeAssistant
homeassistant:
  customize:
# Upstairs Roomba
    switch.roomba_upstairs:
      friendly_name: "Upstairs Roomba"
      icon: mdi:robot-vacuum
    sensor.roomba_upstairs_battery:
      friendly_name: "Upstairs Roomba Battery"
    sensor.roomba_upstairs_status:
      friendly_name: "Upstairs Roomba Status"
      icon: mdi:format-list-bulleted
# Downstairs Roomba
    switch.roomba_downstairs:
      friendly_name: "Downstairs Roomba"
      icon: mdi:robot-vacuum
    sensor.roomba_downstairs_battery:
      friendly_name: "Downstairs Roomba Battery"
    sensor.roomba_downstairs_status:
      friendly_name: "Downstairs Roomba Status"
      icon: mdi:format-list-bulleted

# Switch
switch:
# Upstairs Roomba
  - platform: mqtt
    name: roomba_upstairs
    command_topic: "roomba/upstairs/commands"
    payload_on: "start"
    payload_off: "stop" 
# Downstairs Roomba
  - platform: mqtt
    name: roomba_downstairs
    command_topic: "roomba/downstairs/commands"
    payload_on: "start"
    payload_off: "stop" 

# Sensor
sensor:
# Upstairs Roomba
  - platform: mqtt
    name: roomba_upstairs_status
    state_topic: "roomba/upstairs/status"
  - platform: mqtt
    name: roomba_upstairs_battery
    state_topic: "roomba/upstairs/battery"
    device_class: battery
# Downstairs Roomba
  - platform: mqtt
    name: roomba_downstairs_status
    state_topic: "roomba/downstairs/status"
  - platform: mqtt
    name: roomba_downstairs_battery
    state_topic: "roomba/downstairs/battery"
    device_class: battery

# Group
group:
  roomba_upstairs:
    name: Upstairs Roomba
    entities:
      - switch.roomba_upstairs
      - sensor.roomba_upstairs_status
      - sensor.roomba_upstairs_battery
  roomba_downstairs:
    name: Downstairs Roomba
    entities:
      - switch.roomba_downstairs
      - sensor.roomba_downstairs_status
      - sensor.roomba_downstairs_battery