### Morning Routines ###

automation:
################################################################################
  - id: master_bedroom_lights_morning
    alias: "Routine - Morning - Master Bedroom Lights"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: 
        - device_tracker.network_ians_iphone
        - device_tracker.network_aimees_iphone
        to: 'not_home'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: device_tracker.network_ians_iphone
        state: 'not_home'
      - condition: state
        entity_id: device_tracker.network_aimees_iphone
        state: 'not_home'
    action:
      - service: light.turn_off
        data:
          entity_id: light.master_bedroom_lights
################################################################################

################################################################################
  - id: routine_morning_alarm_disarm
    alias: 'Routine - Morning - Alarm Disarm'
    initial_state: 'on'
    trigger:
    - platform: template
      value_template: >
        {{ states.sensor.time.state == states.sensor.wakeup_alarm_start_time.state }}
    condition:
      condition: state
      entity_id: binary_sensor.workday
      state: 'on'
    action:
      service: alarm_control_panel.alarm_disarm
      data:
        entity_id: alarm_control_panel.home
        code: !secret alarm_code
################################################################################