### Nighttime Routines ###

homeassistant:
  customize:
    binary_sensor.in_bed:
      friendly_name: 'In Bed'

binary_sensor:
################################################################################
  - platform: bayesian
    prior: 0.25
    name: 'in_bed'
    probability_threshold: 0.75
    observations:
      - entity_id: 'binary_sensor.living_room_motion'
        prob_given_true: 0.3
        prob_given_false: 0.7
        platform: 'state'
        to_state: 'off'
      - entity_id: 'sun.sun'
        prob_given_true: 0.7
        platform: 'state'
        to_state: 'below_horizon'
################################################################################

automation:
################################################################################
  - id: routine_night_front_porch_lights
    alias: 'Routine - Night - Front Porch Lights'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sun.sun
        from: 'above_horizon'
        to: 'below_horizon'
    condition:
      condition: and
      conditions:
      # This first condition is slightly redundant. If the automation was
      # triggered because the sun was below the horizon, then why do I need a
      # condition for if the sun is below the horizon? I might remove this later
      # but I'm too afraid of breaking stuff right now, so I'll leave this note.
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: light.front_porch_lights
        state: 'off'
    action:
      - service: light.turn_on
        data:
          entity_id: light.front_porch_lights
          profile: relax
          brightness_pct: 25
          transition: 900
################################################################################

################################################################################
  - id: routine_night_front_door_motion_initial
    alias: 'Routine - Night - Front Porch Motion (Initial)'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.ring_front_door_motion
        from: 'off'
        to: 'on'
    condition:
      condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    action:
  # Transition to this profile, even if on
      - service: light.turn_on
        data:
          entity_id: light.front_porch_lights
          profile: energize
          transition: 1
################################################################################

################################################################################
  - id: routine_night_front_door_motion_idle
    alias: 'Routine - Night - Front Porch Motion (Idle)'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.ring_front_door_motion
        from: 'on'
        to: 'off'
        for:
          minutes: 5
    condition:
      condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    action:
  # Transition back to a preset profile/scene
    - service: light.turn_on
      data:
        entity_id: light.front_porch_lights
        profile: relax
        brightness_pct: 25
        transition: 5
################################################################################

################################################################################
  - id: routine_night_living_room_lights
    alias: 'Routine - Night - Living Room Lights'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sun.sun
        from: 'above_horizon'
        to: 'below_horizon'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: light.floor_lamp
        state: 'off'
    action:
      - service: light.turn_on
        data:
          entity_id: light.floor_lamp
          profile: relax
          brightness_pct: 25
          transition: 900
################################################################################

################################################################################
  - id: routine_night_master_bedroom_lights
    alias: 'Routine - Night - Master Bedroom Lights'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sun.sun
        from: 'above_horizon'
        to: 'below_horizon'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: binary_sensor.worknight
        state: 'on'
      - condition: state
        entity_id: light.master_bedroom_lights
        state: 'off'
    action:
      - service: light.turn_on
        data:
          entity_id: light.master_bedroom_lights
          profile: relax
          brightness_pct: 50
          transition: 900
################################################################################