---
name: Home Assistant CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
  schedule:
    - cron: 0 12 * * *

jobs:
  yamllint:
    name: 🧹 yamllint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: 🚀 Run yamllint
        uses: frenck/action-yamllint@34b4bbcaeabedcfefad6adea8c5bbc42af0e2d47 # v1.5.0

  remarklint:
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Running Remark lint
        uses: 'docker://pipelinecomponents/remark-lint:latest'
        continue-on-error: true
        with:
          args: 'remark --no-stdout --color --frail --use preset-lint-recommended .'

  home-assistant:
    name: 'Home Assistant Core ${{ matrix.version }} Configuration Check'
    needs: [yamllint]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['stable', 'beta', 'dev']
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Copy stub files into configuration folder
        run: cp -R ./.stubs/* .
      - name: Install custom components
        run: bash ./utilities/install_custom_components.sh
      - name: 🚀 Run Home Assistant Configuration Check
        uses: frenck/action-home-assistant@941d5d917f4c1c7a7e7d4087526daf90d53f4437 # v1.4
        with:
          path: '.'
          secrets: ./.stubs/secrets.yaml
          version: '${{ matrix.version }}'

  esphome:
    runs-on: ubuntu-latest
    needs: [yamllint]
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Python 3.13
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: 3.13
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install esphome
          pip list
          esphome version
      - name: Copy secrets stub into configuration folder
        run: cp ./.stubs/secrets.yaml ./esphome/secrets.yaml
      - name: Run esphome on all files
        # yamllint disable rule:line-length
        run: |
          for file in $(find ./config/esphome -type f -name "*.yaml" -maxdepth 1 -not -name "secrets.yaml"); do esphome "${file}" config; done
