---
### Lovelace ###

  # Credit to github.com/basnijholt/home-assistant-config

sensor:
  - platform: filesize
    file_paths:
      - /config/.storage/lovelace

automation:
  - alias: "System - Lovelace - Update"
    trigger:
      platform: state
      entity_id: sensor.lovelace
    action:
      service: shell_command.convert_lovelace