---
### System Maintenance ###

automation:
  ################################################################################
  # Automatically reboot Home Assistant VM once a week. Just in case.
  - id: system_maintenance_reboot
    alias: 'System - Maintenance - Reboot'
    trigger:
      platform: time
      at: '08:00:00'
    condition:
      condition: time
      weekday: sun
    action:
      service: hassio.host_reboot
  ################################################################################
  # Check for certificate renewals daily
  - id: system_maintenance_certificate_renewal
    alias: 'System - Maintenance - Certificate Renewal'
    trigger:
      platform: time
      at: '08:00:00'
    action:
      - alias: 'Wait a random amount of time'
        delay:
          minutes: >
            "{{ range(1, 59) | random | float }}"
          seconds: >
            "{{ range(1, 59) | random | float }}"
      - alias: "Start the Let's Encrypt container"
        service: hassio.addon_start
        data:
          addon: core_letsencrypt
################################################################################
