---
### System Notifications ###

automation:
  ################################################################################
  - id: system_notification_update
    alias: 'System - Notification - Update Available'
    triggers:
      platform: state
      entity_id: update.home_assistant_core_update
    actions:
      action: notify.notify
      data:
        message: 'An update for Home Assistant is available.'
  ################################################################################

  ################################################################################
  - id: system_notification_new_device
    alias: 'System - Notification - New Device'
    triggers:
      - trigger: event
        event_type: device_tracker_new_device
    actions:
      - service: notify.notify
        data_template:
          message: >
            Home Assistant has discovered a new device:
            {{trigger.event.data.entity_id}}
          title: New Device
  ################################################################################

  ################################################################################
  - id: system_notification_start
    alias: 'System - Notification - Home Assistant Start'
    triggers:
      platform: homeassistant
      event: start
    actions:
      action: notify.notify
      data:
        message: 'Home Assistant has Started!'
  ################################################################################

  ################################################################################
  - id: system_notification_certification_expiration
    alias: 'System - Notification - Home Assistant Certificate'
    triggers:
      platform: template
      value_template: >
        {{ states.sensor.ssl_certificate_expiry.state | int  <= 14 }}
    conditions:
      condition: template
      value_template: >
        {{ states.sensor.ssl_certificate_expiry.state != "unknown" }}
    actions:
      action: notify.notify
      data_template:
        message: >
          Home Assistant's certificate expires in {{ states.sensor.ssl_certificate_expiry.state }} days.

################################################################################
